### ISSUE TITLE
cordovaProj.raw.create is not a function

### ISSUE THREAD

**Issue by IsaacShrestha** [isleofcode/ember-cordova#10]
I am getting "TypeError: cordovaProj.raw.create is not a function", when ever I run ember install ember-cordova. I am running EmberJS and Cordova in ubuntu 16. I have done all the installation of cordova following its documentation and also set path as specified, also checked for any possible solution but I am still getting this error and it is not creating ember-cordova directory in my Ember project. Please help me.

**Comment by wukongrita** [comment]
Any update on this? I've tried to downgrade, but still no luck..

**Comment by IsaacShrestha** [comment]
I tried downgrading too but it didn't help. Unfortunately, I switched to Corber.

**Comment by alexblom** [comment]
This is related to using a higher version of cordova-lib. Try downgrading to 7.0.1 vs 7.1.0.

I've fixed the issue in corber if you want to port it here: https://github.com/isleofcode/corber/commit/cf1e26105a14cc6923e989ad6d15610d314ed442

**Comment by wukongrita** [comment]
seems still not working...

```
$ cordova -v
7.0.1
```

```
$ ember i ember-cordova@1.0.4
NPM: Installed ember-cordova@1.0.4
installing ember-cordova
Initting ember-cordova directory
cordovaProj.raw.create is not a function
TypeError: cordovaProj.raw.create is not a function
```

**Comment by feanor07** [comment]
still no success at this. will there be any fix at all?

**Comment by alexblom** [comment]
Cordova is version locked to 7.0.1 in the latest ember-cordova release. If you need higher, you could appropriate the same patch in corber or just migrate there.
