### ISSUE TITLE
Paths issue

### ISSUE THREAD

**Issue by and2** [isleofcode/ember-cordova#103]
Hi, I'm hitting this issue on a new ember-cli 2.7.0 project while running ember cdv:build.
Have you seen this before?

`TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at blabla/node_modules/ember-cordova/index.js:63:29
    at Array.forEach (native)
    at CoreObject.module.exports.treeForPublic (blabla/node_modules/ember-cordova/index.js:62:13)
    at CoreObject._treeFor (blabla/node_modules/ember-cli/lib/models/addon.js:373:33)
    at CoreObject.treeFor (blabla/node_modules/ember-cli/lib/models/addon.js:341:21)
    at blabla/node_modules/ember-cli/lib/broccoli/ember-app.js:498:20
    at Array.map (native)
    at EmberApp.addonTreesFor (blabla/node_modules/ember-cli/lib/broccoli/ember-app.js:496:30)`

**Comment by and2** [comment]
A little update, this only occurs for ember-cordova 0.2.1. The build is successful on 0.2.0.

**Comment by RobIsHere** [comment]
Hi! I'm struggling with this, too. Also at ember-cli 2.7.0

this.project.CORDOVA_PLATFORM
is undefined in index.js line 47.

**Comment by RobIsHere** [comment]
Maybe the reason is:
Commit: fix(build/serve): take default cordovaPlatform

**Comment by RobIsHere** [comment]
Ok. Resolved it. But I'm not sure if you want to re-add or move away from this?
However: the quick fix is...

After:
    var platform = getPlatform(this.project.config(), options);

Add:
    project.CORDOVA_PLATFORM = platform;

At both files:
lib/commands/build.js
lib/commands/serve.js

**Comment by RobIsHere** [comment]
also this:
ERROR: Expected a cordova plugin to be installed that was not: undefined: Not found in config.xml. You probably need to run ember cdv:plugin add undefined.

**Comment by AmilKey** [comment]
this PR fix it https://github.com/isleofcode/ember-cordova/pull/104

**Comment by alexblom** [comment]
Thanks, merged and pushing a release.

**Comment by RobIsHere** [comment]
I pulled the new version. It contains tmp and dist build files in none_modules/ember-cordova somehow.

No problem, deleted them. Just to let you know.
