### ISSUE TITLE
Whitelist plugin validation broken

### ISSUE THREAD

**Issue by RobIsHere** [isleofcode/ember-cordova#106]
Commit a58181b2a7c5372ccf7a8cef8a1c9f0e458f1487 renamed a property in tasks/validate-plugin.js:
pluginName => desiredKeyName

This breaks validation in the command serve.js where "pluginName"
is still used to initialize the Validator. (Line 83)

**Comment by alexblom** [comment]
I've just finished merging in #98 which included fixes to this. Thanks for reporting, we've finished most of the throwing around internals now.
