### ISSUE TITLE
ember cdv:serve not working without baseURL

### ISSUE THREAD

**Issue by RobIsHere** [isleofcode/ember-cordova#107]
When baseURL is removed according to http://emberjs.com/blog/2016/04/28/baseURL.html#toc_upgrading
ember cdv:serve fails with an "undefined" error.

ember serve continues to work.

ember-cli 2.7.0
ember-cordova 2.2.0

**Comment by alexblom** [comment]
Thanks, this should now be rectified in 0.2.4.
