### ISSUE TITLE
Empty cordova.js file when running ember cdv:serve

### ISSUE THREAD

**Issue by and2** [isleofcode/ember-cordova#109]
When running `ember cdv:serve` on ember-cordova 0.2.0, the cordova.js file has just the following comment: `No-op script for when serving to both browser and Cordova device.`

**Comment by alexblom** [comment]
Can you try with 0.2.4 and let me know if you still have this issue?

**Comment by and2** [comment]
Thanks so much for having a look at this issue! Just tried it now on a new ember app with ember-cordova 0.2.4 and unfortunately the problem is still there for me. Once `ember cdv:serve` is executed `www/cordova.js` is replaced with just that comment.

**Comment by and2** [comment]
I've just seen that `ember cdv:serve` serves `cordova.js` when accessed over `http://IP:port` from `node_modules/ember-cordova/public/cordova.js` which I believe is not the right path. I've tried to find what triggers this, but no luck so far.

**Comment by Dragsbaek** [comment]
Same issue here

**Comment by alexblom** [comment]
Thanks, I've managed to replicate this. Should be able to figure out a fix in the next day or two.

**Comment by alexblom** [comment]
Upgrade to 0.2.6 and you are good.

**Comment by and2** [comment]
Nice one, cheers for that!
