### ISSUE TITLE
iOS icons not being generated

### ISSUE THREAD

**Issue by AlbertoHdezCerezo** [isleofcode/ember-cordova#11]
Hi, I am trying to generate iOS icons and splash image for my Ember Cordova application with no result.

I have followed all the instructions, and it even works perfectly for Android, but when running `ember cdv:make-icons` I get the message:

> ember-cordova: Generating icons for android, ios

And android icons are generated but only for Android. Any idea what could be the issue?

**Comment by alexblom** [comment]
Are you still seeing this problem? Do you see any entries to iOS, and was the iOS platform installed and listed in your config.xml prior to running the command? 

Thanks
