### ISSUE TITLE
deviceready race condition

### ISSUE THREAD

**Issue by jbrown** [isleofcode/ember-cordova#115]
My application route is as follows:

```javascript
import Ember from 'ember';
import subscribe from 'ember-cordova/utils/subscribe';

const {
  inject,
  Route
} = Ember;

export default Route.extend({
  cordova: inject.service(),

  logReady: subscribe('cordova.deviceready', function() {
    window.navigator.splashscreen.hide();
  })
});
```

I sometimes get a fatal error like this...

<img width="1193" alt="screen shot 2016-08-15 at 5 37 24 pm" src="https://cloud.githubusercontent.com/assets/47560/17680635/29249ca2-630f-11e6-9f07-b1a9f2f4996a.png">

After reading the cordova service code I saw the `ready` method and once I switched to that I had no further issues.

```javascript
activate() {
  this.get('cordova').ready().then(() => {
    window.navigator.splashscreen.hide();
  });
}
```

Any thoughts on why subscribing to `deviceready` would cause that? I'm happy to update the docs to suggest using that `ready` promise, it seems like a more reliable approach.

**Comment by anulman** [comment]
@jbrown Can you confirm what version you're on? Tested on latest (0.2.6) and could not replicate.

Based on the stacktrace (specifically, the reference to `run.join` & a missing context) my hunch is you're using something prior to ~0.1.13, when this commit was merged & released: https://github.com/isleofcode/ember-cordova/commit/186cb26698337418a7f2db6291663885db5395ee .

Else, let's get hunting 😸

**Comment by alexblom** [comment]
I'm going to close this given probably old version and old-ness. Please reopen if you are still having issues.
