### ISSUE TITLE
command line parameter for setting reloadUrl does not work

### ISSUE THREAD

**Issue by RobIsHere** [isleofcode/ember-cordova#116]
The -r command line parameter does not work. Only the environment/config works.

Your plugin helps us a lot!
(Although this is an issue tracker: just writing about the things that do not work, feels not right at all ;)

**Comment by alexblom** [comment]
I appreciate it. I noticed the reload-url last night as well, I'm hoping to have a fix in this week.

Hopefully you don't need the -r param very much though, and the IP is being detected for you :)

**Comment by RobIsHere** [comment]
Acually i'm going to use it a lot. But i set it in config and everything is ok.

I'm working on an app that has 1.2GB node_modules deps. And a lot of Sass processing.

ember serve takes 60s to serve a code update on my macbook pro. On my ubuntu dev box its only 5s. So i will just recompile the "hull" on my mac book, get it on the device and connect livereload to my ubuntu box.

I'm just explaining this because i noticed that maybe the option to just build a "live reload app container" with ember cdv:build --reloadable whatever would fit my workflow ;)

For me it would also make sense to batch-compile and run different platforms. Because i could just issue the command and all ios, android, tablet etc would reload at once. I hope i have some time to help when we will have shipped our application.

**Comment by alexblom** [comment]
`I'm just explaining this because i noticed that maybe the option to just build a "live reload app container" with ember cdv:build --reloadable whatever would fit my workflow ;)`

So I've actually been working on this, am hoping to have it out by Friday. I think its saner for most workflows, the actual built app in cdv:s is now used only so the initializer can redirect to the right url anyway.

**Comment by alexblom** [comment]
This should be resolved in 0.2.7.

This doesn't resolve your batch compile, and feel free to open an Issue for that.

Live reload now implements an app that is just a skinny container, so this may solve some of your other build challenges.
