### ISSUE TITLE
Passing extra arguments when building cordova?

### ISSUE THREAD

**Issue by jviney** [isleofcode/ember-cordova#118]
Thanks for all the hard work on this project 👍 👍 

I'm using it with cordova-hot-code-push, which supports passing extra arguments to `cordova build` for different environments. [Example](https://github.com/nordnet/cordova-hot-code-push/wiki/Build-options). Eg:

`cordova build -- chcp-dev`

This doesn't work:

`ember cdv:build -- chcp-dev`

From looking at the code it's pretty obvious it won't work. Is it possible to pass through the `chcp-dev` option in another way?

Alternatively, the changes being made as a result of passing through `chcp-dev` could be put into hooks.

Regards,
-Jonathan.

**Comment by jviney** [comment]
I'm happy to close this. Using a hook instead.

**Comment by alexblom** [comment]
Thanks for reporting. I do have a pending task for myself to make sure we are supporting the full suite of flags.
