### ISSUE TITLE
Environment and platform information in the hooks

### ISSUE THREAD

**Issue by RobIsHere** [isleofcode/ember-cordova#124]
It would be great to have this information. I have about ten environments defined and every env needs special treatment.

Maybe by binding this as context to the hook function? That would be backwards compatibel.

**Comment by alexblom** [comment]
I'm going to close it and keep #93 open, I see them as being the same work package. Perhaps we should rename that issue to be clearer.

Ultimately, we're working on an abstraction above config.xml that allows for env + versioning config, and us to track some custom values for live reload/builds.
