### ISSUE TITLE
ember cdv:serve with option to turn off cordova build

### ISSUE THREAD

**Issue by RobIsHere** [isleofcode/ember-cordova#125]
It would be great if there is an option to turn off cordova build.

The issue is: If i simply do ember serve from my linux box, it includes this no-op cordova.js
But i need the full one. Because i serve from the linux box to the iphone.

So i have to run ember cdv:serve on my linux box to get the full cordova.
Which in turn fails building ios on the box. (Android also not installed)

Should i make a pr?
Would you have a preference for a certain option name? --skip-cordova-build / short: -scb ?

**Comment by alexblom** [comment]
The timing of this is great. I think if you work off my develop branch, this will already be handled for you. If not, it should be an easier base to extend from. 

I'm qa'ing and pushing it as a release today.

**Comment by alexblom** [comment]
Let me know if the latest (0.2.7) resolves these issues for you. I think in your case you still need to open skip the cordova build. 

I'd be fine with --skip-cordova-build && -scb. 

Thanks :)

**Comment by RobIsHere** [comment]
Is there some easy way i could make "serve" address different platforms at the same time. So you can see livereload on android and ios simultaneously?

I made some experiments. But it seems the platforms are too different. It also seems that the content of the platform_www directories is somehow "namespaced" using subdirectories.

Maybe combining them is possible? Just using different cordova.js and cordova_plugins.js. If you have any experience already gathered in this, please let me know. I will do some experiments.

**Comment by alexblom** [comment]
There probably is, but I haven't put much thought into that problem yet. I imagine you'd need two instances of serve running: the actual cordova.js file differs by platform, as do the plugins. I'm pretty sure you could just run two serve processes on different ports today.

If it is not simple, it may be easier to park that until we clean up serve (or I can give you some notes). 

Hope this helps,

**Comment by alexblom** [comment]
Fixed in latest release :)

**Comment by RobIsHere** [comment]
Great! Thank you, Alex!
