### ISSUE TITLE
Hide Splash Screen implementation issue

### ISSUE THREAD

**Issue by clevernyyyy** [isleofcode/ember-cordova#127]
Hi, maybe I'm simply not following the documentation, but I've added this to my application route and I'm still seeing the splash screen post-cordova deployment.

```js
import Ember from 'ember';
import SplashscreenMixin from 'ember-cordova/mixins/device/splashscreen';

export default Ember.Route.extend(SplashscreenMixin, {
  splashScreenService: Ember.inject.service('device/splashscreen'),
  beforeModel: function(transition){
    this.splashScreenService.hide;
```

**Comment by alexblom** [comment]
I just went through and tested, it seems to be working here. Two things though:

1) `this.splashScreenService.hide` should read as `this.splashScreenService.hide();`. Can you confirm?; and
2) You don't need both the Mixin and the Service. Either/or is fine.

**Comment by clevernyyyy** [comment]
Hmmm, when I do:

```
import Ember from 'ember';

export default Ember.Route.extend({
  splashScreenService: Ember.inject.service('device/splashscreen'),
  beforeModel: function(transition){
    this.splashScreenService.hide();
```

I get an error:  
`ember.debug.js:30240 Error while processing route: index this.splashScreenService.hide is not a function TypeError: this.splashScreenService.hide is not a function`

**Comment by alexblom** [comment]
I just took a closer look at your code sample. I think you need to replace: 

`this.splashScreenService.hide();`

with

`this.get('splashScreenService').hide();`

**Comment by clevernyyyy** [comment]
There's no errors anymore.  Unfortunately, I still see the splash screen.  This is from a `ember-cli-cordova` migration.  Maybe I'll just try a fresh repo.

**Comment by mrosata** [comment]
I can't confirm for @clevernyyyy but this all worked for me and I was having a similar issue, and tested out the steps in this thread. Got that same error, changed to `this.get('...` and it's now working. Thanks!

:+1:

**Comment by alexblom** [comment]
@clevernyyyy Please do, and let me know the outcome.

If it still fails, I'd consider running remote console, and executing `navigator.splashscreen.hide()`. At least then we can identify if the service is failing, or you have broader splash implementation issues.

**Comment by alexblom** [comment]
I'm going to close this given mrosata's feedback. Please re-open if you are having the issue still.
