### ISSUE TITLE
app and vendor assets missing on iOS.

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#128]
```
ember-cli: 2.7.0
node: 5.3.0
os: darwin x64
cordova: 6.2.0
ember-cordova: 0.2.7
```
[app].js/css & vendor.js/css files are not in correct paths.
<img width="1094" alt="screen shot 2016-08-22 at 10 53 49 pm" src="https://cloud.githubusercontent.com/assets/309076/17881762/ca5e23f6-68bc-11e6-9be0-53bd7b405df2.png">
<img width="954" alt="screen shot 2016-08-22 at 10 53 55 pm" src="https://cloud.githubusercontent.com/assets/309076/17881769/cde83138-68bc-11e6-92d1-02dd0e20256b.png">

**Comment by alexblom** [comment]
I'm having trouble replicating this. Can you perhaps first confirm that app.js / vendor.js are in ember-cordova/cordova/www for me?

If you want to message me on the ember-slack, @alexblom, it may be easier if I quickly ScreenHero to see this.

**Comment by alexblom** [comment]
I'm going to close this as it was resolved on the ember-slack #e-cordova channel. The issue was usage of rootUrl, which is documented in the main readme.
