### ISSUE TITLE
Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by jcmartinezdev** [isleofcode/ember-cordova#13]
Hi all,

I'm having an issue when connecting to a remote URL with the iOS platform, the error I get when I check safari is: ```Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.```

I couldn't find a way to solve it, is there a way of specifying the Origin? like using the bundle or anything from the app?

Thanks

**Comment by alexblom** [comment]
You typically want to have installed the InAppBrowser plugin to enable opening external URLS. Let me know if that resolves your problem.
