### ISSUE TITLE
ERROR ember-cordova with cordova raw when running ember cdv commands

### ISSUE THREAD

**Issue by MondeSameWave** [isleofcode/ember-cordova#130]
This is what i get when I try to run ember cdv:platform add ios

```
Preparing to add platform ios
ERROR ember-cordova with cordova raw
Current working directory is not a Cordova-based project.
```

My directory looks like this:
```
action-chat-client
|-README.md
|-bower_components
|-ember-cli-build.js
|-package.json
|-tests
|-app
|-config
|-ember-cordova
|-public
|-tmp
|-bower.json
|-dist
|-node_modules
|-testem.js
|-vendor
```

**Comment by MondeSameWave** [comment]
Reinstalling NPM package fixed it

**Comment by alexblom** [comment]
Thanks. This is almost always due to a faulty cordova install/project (e.g. www dir missing).

**Comment by Ramblurr** [comment]
What else could cause this? All of a sudden I can't build my project as ember cordova is failing with this error. I've reinstalled all the things from scratch to no avail.

**Comment by Ramblurr** [comment]
I have to add that this is one of the most unhelpful error messages ever hah.

```ERROR ember-cordova with cordova raw```

**Comment by MondeSameWave** [comment]
Use Xcode to build to device/emulator. You can open xcode in your terminal using
ember cdv:open then selectingyour device and tapping the play button in xcode.

Currently I cannot build within the terminal to iPhone 6 but it does work with iPhone 5

**Comment by Ramblurr** [comment]
Adding an empty file named `.cordova` to ember-cordova/cordova/ fixed this  problem for me.

Apparently in a newer version of cordova, they changed how the cordova dir detection works. Of course older pre-existing cordova project dirs didn't get updated.


```
touch ember-cordova/cordova/.cordova
```
