### ISSUE TITLE
Fails to npm install v 0.2.8

### ISSUE THREAD

**Issue by optikalefx** [isleofcode/ember-cordova#132]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/sean/n/bin/node" "/Users/sean/local/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.3.9
npm ERR! path /Applications/MAMP/htdocs/wb-conference/node_modules/ember-cordova/node_modules/svg2png/node_modules/yargs/node_modules/cliui/node_modules/strip-ansi/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Applications/MAMP/htdocs/wb-conference/node_modules/ember-cordova/node_modules/svg2png/node_modules/yargs/node_modules/cliui/node_modules/strip-ansi/node_modules/ansi-regex' -> '/Applications/MAMP/htdocs/wb-conference/node_modules/ansi-regex'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/wb-conference/npm-debug.log
sclark-3:wb-conference sean$ ember s
```

and then upon running, of course svg2png is missing.

**Comment by alexblom** [comment]
Wonderful. I've grown somewhat frustrated with the usage of svg2png, so have been thinking about abstracting its usage to another add-on. I think you just gave me the last push to get this done. 

Abstracting it will also allow us to support node 0.x easily.

**Comment by optikalefx** [comment]
I'm not sure if you've seen these, but I currently use these libs with my ember-cordova installation https://github.com/AlexDisler/cordova-icon and https://github.com/AlexDisler/cordova-splash which I belive do not use svg2png

**Comment by alexblom** [comment]
I'm vaguely familiar. The goal with including it in the main library was both to have a library that more easily interacts with the CLI, and to not require pre-install steps like imagemagick.

Right now, I'm thinking of simply pulling the icon/splash commands to their own add-on that will work with ember-corodva.

**Comment by optikalefx** [comment]
Ah, good call. I forgot imagemagick was a dep. that's a bit heavy for people.

**Comment by alexblom** [comment]
I'd be curious to see if 0.2.9 fixes this. I'd be happy to debug it further, but svg2png is no longer required via npm.

**Comment by alexblom** [comment]
I'm going going to close this with the assumption 0.2.9 solved your issues. If not, please re-open and I'll look further.
