### ISSUE TITLE
Build for android fails due to existing www dir

### ISSUE THREAD

**Issue by optikalefx** [isleofcode/ember-cordova#140]
`EEXIST: file already exists, mkdir '<my project>/ember-cordova/cordova/www'`  

I've built android before, but for some reason, I'm guessing due to an update, it fails because of this directory error.  

I use the master branch from this repo.

**Comment by optikalefx** [comment]
I guess that alias www was there from before. Once deleted it seems to be fine. I'll keep this open for a bit more testing

**Comment by alexblom** [comment]
Thanks - how did it shake out?

**Comment by optikalefx** [comment]
Things are fine, I guess through various upgrades an earlier version added a www alias, and is no longer needed. But when exists it fails. No issues after manual removal.
