### ISSUE TITLE
{{rootUrl}} isn't getting rendered on the website.

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/ember-cordova#149]
On http://embercordova.com/pages/setup_guide

<img width="583" alt="screenshot 2016-09-23 02 51 39" src="https://cloud.githubusercontent.com/assets/48965/18761767/d780714e-8138-11e6-95fb-919a9ee04297.png">

**Comment by alexblom** [comment]
Thanks for reporting. Since rectified.
