### ISSUE TITLE
cdv:make-icons changes the config.xml indentation to 2 and strips out xml comments.

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/ember-cordova#158]
My config files goes from the cordova default of 4 to 2 spaces and then strips out my comment. Turning:

```xml
<!-- allow-naviagtion is needed for live-reload. It gets removed before the build. -->
<allow-navigation href="*" />
```

into 

```xml
<allow-navigation href="*" />
```

**Comment by alexblom** [comment]
Thanks. @jordanyee is probably most familiar here.

**Comment by jordanyee** [comment]
@kitsunde I just had a chance to take a look at these issues. 

They're both issues related to splicon which handles the icon and splash image generation and config.xml updating. So I've created issues in that repo you can follow there:

- [Build Config with Cordova Tab Width Default](https://github.com/isleofcode/splicon/issues/11)
- [Maintain Comments in Config](https://github.com/isleofcode/splicon/issues/12)
