### ISSUE TITLE
ember-cordova should probably add itself to watchman ignore.

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/ember-cordova#159]
From https://github.com/isleofcode/ember-cordova/issues/154#issuecomment-249947818

Whenever I run cordova and have `cdv:serve` running it cause successive rebuilds unless I update `.watchmanconfig` to:

``` json
{
  "ignore_dirs": ["tmp", "dist", "ember-cordova"]
}
```

Maybe it should just ignore the `ember-cordova/tmp-livereload` and `ember-cordova/cordova`.

**Comment by alexblom** [comment]
Agreed. I'm unsure why I have not been affected by this locally, but agreed and will put it into my own roadmap.
