### ISSUE TITLE
Cannot add additional CLI params when adding plugins.

### ISSUE THREAD

**Issue by Shaneprrlt** [isleofcode/ember-cordova#161]
I was trying to add the phonegap-facebook-plugin to my project, however, this plugin requires passing additional parameters when adding to a project, (Facebook APP_ID and APP_NAME), however, when I run `ember cordova:plugin add phonegap-facebook-plugin --variable APP_ID=**** --variable APP_NAME=****`, I get an error from the plugin saying I have not passed those required params. I figure there has to be many cases where plugins require additional CLI arguments to be passed.

**Comment by alexblom** [comment]
Please excuse my delay - really unreliable internet while travelling.

For now you can use the proxy command:
`ember cdv plugin add $STUFF` vs `ember cdv:plugin add $STUFF`

I agree this should be supported though. Thanks for reporting :)

**Comment by Shaneprrlt** [comment]
Yes! You helped me a few nights ago on the #e-cordova slack, thanks! Using the proxy command worked perfectly! So even though yeah, I should be able to add those additional params through the `cdv:plugin` command, it's not too pressing, as not many plugins require additional params. The facebook plugin I used has been the only one so far I've encountered.

**Comment by alexblom** [comment]
Fixed in 0.3.5
