### ISSUE TITLE
.gitkeep in www gets deleted on build

### ISSUE THREAD

**Issue by tavosansal** [isleofcode/ember-cordova#163]
There is a .gitkeep file in the ```ember-cordova/cordova/www``` folder that gets created when the addon is installed. If you run ```ember cdv:build``` however, that .gitkeep file gets deleted. This is not a problem until you commit changes and do a fresh clone of the repo. Since the www folder does not exist anymore (because .gitkeep is gone) then all of the ember cordova functionality does not work until you manually create the www folder again and add the .gitkeep file back.
Thank you.

**Comment by alexblom** [comment]
Thanks for reporting - that will definitely cause cloning issues. I'm just catching up on backlog but will get to this ASAP.

**Comment by alexblom** [comment]
Fixed in 0.3.4 :)
