### ISSUE TITLE
Multiple fingerprint on plugins files

### ISSUE THREAD

**Issue by gmarquet** [isleofcode/ember-cordova#164]
I added the geolocation plugin and i have  files in ember-cordova\cordova\www\plugins\cordova-plugin-geolocation\www\android which are: 

```
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793-94c066d78d1daff6395b653635d1a793.js
PositionError-94c066d78d1daff6395b653635d1a793.js
```

**Comment by alexblom** [comment]
Thanks for reporting. Are you having this issue with other plugins, or just the one?

**Comment by gmarquet** [comment]
I was unable to reproduce on a clean project with an other machine (i am using  docker so it shouldn't matter). 
I'll try to get more info tomorrow.

**Comment by utilityboy** [comment]
@alexblom this is the issue I was having as well.  For me it was the barcode scanner plugin

**Comment by Dragsbaek** [comment]
I have the same issue with all plugins

**Comment by alexblom** [comment]
Thanks - I'm going to prioritize this as an issue. I'm still having trouble getting a stable replication case, but I'll see what I can find.

**Comment by utilityboy** [comment]
@alexblom I'm here this week.  Anytime.  Can also screenhero and I'll try to reproduce for you.

**Comment by alexblom** [comment]
Thanks all. I've finally got a local replication case, so going to go in further.

**Comment by utilityboy** [comment]
In the meantime, see:

https://github.com/isleofcode/ember-cordova/issues/181#issuecomment-255542216

**Comment by alexblom** [comment]
Fixed in latest release
