### ISSUE TITLE
cordova:open --platform android seem to expect a .project file that isn't generated by cordova.

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/ember-cordova#171]
The culprit seems to be this:

https://github.com/isleofcode/ember-cordova/blob/656daed5b0d877e1354b94fb7dd29ee05005690c/lib/tasks/open-app.js#L26

It's not created by `cordova:prepare` or `cordova:build --platform android`. My best guess is that it's an Eclipse specific file https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore#L15

**Comment by KirillSuhodolov** [comment]
@kitsunde same issue

**Comment by alexblom** [comment]
This is definitely an error / broken IDE assumption. Until it is fixed, your best solution is to either pop open the IDE manually, or run `ember cdv run --platform=android --device`

**Comment by shaunc** [comment]
Perhaps silly newbie question: how does one "pop open IDE manually"? In Android studio it wants me to create new, open or import, so I imported `[root-project]/ember-cordova/cordova/platforms/android` ... which seems to work. However, when I try to run, it opens "select deployment target" dialog, claiming the APK supports only ", all, armeabi-v7a" not x86 -- yet I see that cdv:build did build `...build/outputs/apk/android-x86-debug.apk`. Can you explain where Android studio is getting the path to the APK among the confusing plethora of configuration files? :)

**Comment by alexblom** [comment]
This was finally rectified in 0.4.8.

@shaunc Re: issues, happy to take documentation issues - we kind of assume Android env setup outside of this project but are discussing ways to make that easier now we have a stable cli. Have you worked through the Cordova Env setup guides? https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

I'm closing this issue as it resolves the named concern, feel free to create one if something else comes up.
