### ISSUE TITLE
How to run the project in the emulator with live-reload?

### ISSUE THREAD

**Issue by listepo** [isleofcode/ember-cordova#173]
Now `ember cdv:serve`  only starts dev server and not deploy on the emulator

**Comment by alexblom** [comment]
To my knowledge `ember cdv:s` would always just create a build & then run server, it was always up to you to run an emulator via cli or Xcode.

Has prior behaviour changed or am I missing something?

**Comment by listepo** [comment]
Maybe it necessary to create a command like ```react-native run-ios``` that will start the simulator and dev server?

**Comment by alexblom** [comment]
At the moment we achieve this by proxy, for example 'ember cdv run ios --emulator'

The lack of colon let's you run a standard Cordova command. Ive updated this with a cli output on the upcoming release.
