### ISSUE TITLE
The ember-cordova/pages/setup_guide.md is not rendering correctly

### ISSUE THREAD

**Issue by JonForest** [isleofcode/ember-cordova#174]
There is some XML in an example on this page.  It looks fine on the .md file in github, but is not rendering correctly on the website (http://embercordova.com/pages/setup_guide - bottom of the page)

Sorry, this was my PR that caused this, but not sure how to fix it.

**Comment by alexblom** [comment]
No worries - looks like it was fixed along the way anyway :)
