### ISSUE TITLE
How to run live reload on a usb android device

### ISSUE THREAD

**Issue by matthellstrom** [isleofcode/ember-cordova#176]
Just installed ember-cordova for the first time, and I'm trying to run livereload on my android usb device, what do I need to do to get it to recognize it? This is my first experience of developing on an android. I have debugging on the tablet set up right, because I loaded Android Studio and did a little test app and it runs on the tablet. Just not sure how to specify where I want livereload to run.

**Comment by kitsunde** [comment]
```bash
ember cdv:serve --live-reload-host "192.168.99.4" --platform android
ember cordova run android --device --nobuild
```

Replace the host with your actual network ip. If `ember cordova run` is giving you trouble (it does for me on macOS Sierra for iOS currently) you can also just run it through android-studio when it has been build with `cdv:serve`.

**Comment by alexblom** [comment]
Just to chime in, most of the time setting the ip should not be required and it will be automatically detected. It should be as simple as running the serve command, and then flashing it to your device or running an emulator. 

Are you still having troubles @matthellstrom

**Comment by matthellstrom** [comment]
Oh sorry, yes I did get it to work. I didn't understand how to flash it to my device but I figured it out. Thanks for the follow up.

**Comment by alexblom** [comment]
:)
