### ISSUE TITLE
The option '--name' is not registered with the install command. Run `ember install --help` for a list of supported options.

### ISSUE THREAD

**Issue by IAmJulianAcosta** [isleofcode/ember-cordova#177]
```
$ ember --version
ember-cli: 2.8.0
node: 6.8.1
os: win32 x64
```

```
$ ember new test-app
cd test-app
```

```
$ ember install ember-cordova --name=AppName --cordovaid=com.isleofcode.app --templatePath=../template
The option '--name' is not registered with the install command. Run `ember install --help` for a list of supported options.
The option '--cordovaid' is not registered with the install command. Run `ember install --help` for a list of supported options.
The option '--templatePath' is not registered with the install command. Run `ember install --help` for a list of supported options.
```

**Comment by glbatistabh** [comment]
I have the same problem.

> ember --version
> Looks like you have a different program called watchman, falling back to NodeWatcher.
> Visit http://ember-cli.com/user-guide/#watchman for more info.
> ember-cli: 2.8.0
> node: 6.8.1
> os: linux x64

> ember new test-app
> cd test-app

> ember install ember-cordova --name=AppName --cordovaid=com.isleofcode.app --templatePath=../template
> The option '--name' is not registered with the install command. Run `ember install --help` for a list of supported options.
> The option '--cordovaid' is not registered with the install command. Run `ember install --help` for a list of supported options.
> The option '--templatePath' is not registered with the install command. Run `ember install --help` for a list of supported options.

**Comment by kitsunde** [comment]
That log output isn't an error, it's just a warning from ember-cli. It still works find and should continue after.

However if you have a standard ember setup then ` --templatePath=../template` will cause it to fail. 

What's the complete log output?

**Comment by glbatistabh** [comment]
> That log output isn't an error, it's just a warning from ember-cli. It still works fine and should continue after.

Answer: Yes .. just a warning that the **option do not exist**! That is, it does not work.


> What's the complete log output? Does it work without --templatePath=../template?

Answer: It does not work!

**Comment by kitsunde** [comment]
@glbatistabh You misunderstand. A completely separate project ember-cli thinks it doesn't work, but ember-cordova itself will accept the argument just fine regardless of what ember-cli is saying.

Is there no other log output?

**Comment by kitsunde** [comment]
Anyways here's a completely new setup on Ubuntu 14.04, with a fresh install of both ember and cordova completing the setup without any issues: https://asciinema.org/a/dix6sugs5rxyyrjaqmmgza9c2

```bash
$ ember --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.8.0
node: 4.5.0
os: linux x64
```

**Comment by glbatistabh** [comment]
Can I ask you a favor?
You can continue the video and build an example of APP where the battery
status will be displayed on the screen?

* Android platform
* Cord-plugin-battery-status plugin

thank you VERY MUCH!
It will help me a lot!

-- 


2016-10-18 11:28 GMT-02:00 Kit Sunde <notifications@github.com>:

**Comment by alexblom** [comment]
Thanks for jumping in on this @kitsunde. He is right that this is coming externally from ember-Cordova and we still take the params fine. 

I'm going to close this issue but if you are still struggling with the other questions feel free to open a new one.
