### ISSUE TITLE
The App crashes after returning from Facebook

### ISSUE THREAD

**Issue by denzo** [isleofcode/ember-cordova#186]
I am using version `0.3.3`. I have a login with Facebook in the app. The app crashes after it goes to the Facebook app and back.

Any thoughts on what is causing that?

**Comment by alexblom** [comment]
I'm not sure / would need to see some implementation. Feel free to DM on the ember-slack if you want to keep it private.

If you are running in debug mode, your console.logs/logs will output to a log file in the cordova directory. Track that down and see if anything funny is happening?

**Comment by alexblom** [comment]
I'm going to close this given inactivity, but please re-open for visit us on the ember-slack if you are still having issues.
