### ISSUE TITLE
Plugins stopped working after upgrading to 0.3.7

### ISSUE THREAD

**Issue by denzo** [isleofcode/ember-cordova#187]
![screen shot 2016-11-12 at 10 04 59 pm](https://cloud.githubusercontent.com/assets/1874772/20237373/357c5692-a924-11e6-8fd7-4961eb58ce90.png)

**Comment by alexblom** [comment]
Thanks. Just to make sure, did you completely nuke your plugins/platforms directory after upgrade? 

I'm trying to create a replication case here, but am concerned it is coming from a clean project.

**Comment by denzo** [comment]
When I wrote the issue I didn't nuke plugins/platforms directory. I have just nuked them now and ran `ember cdv:platform add ios` and then `ember cdv:server`. Still getting the same errors.

Yes it does happen in live reload.

**Comment by alexblom** [comment]
Upgrade to 0.3.8 and you are good to go
