### ISSUE TITLE
Files are missing after the build and running on android.

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#188]
The assets paths are broken on 0.3.7

**Comment by v3ss0n** [comment]
Tested with totally new ember-app and everything is broken. How can i downgrade ?

**Comment by alexblom** [comment]
To downgrade just change the version in your package.json

**Comment by v3ss0n** [comment]
Thanks  , the problem is need to remove the `{{rootUrl}}`
