### ISSUE TITLE
My application does not load any route.

### ISSUE THREAD

**Issue by jhonathas** [isleofcode/ember-cordova#193]
I have this route setting that works normally in the browser:

> import Ember from 'ember';
> import config from './config/environment';
> 
> const Router = Ember.Router.extend({
>   location: config.locationType,
>   rootURL: config.rootURL
> });
> 
> Router.map(function() {
>     this.route('home', {path: '/'});
> });
> 
> export default Router;

When I send it to my cell phone, the app screen is blank. I noticed that if I put a text in Ember's index.html, the text appears. Do I need to configure anything else to work?

**Comment by alexblom** [comment]
What version are you running / can you confirm you do not have presence of {{rootURL}} or {{baseURL}} in your app/index.html?

This is the most common cause, but only the most recent version has explicit warnings for it.

**Comment by jhonathas** [comment]
When I read about the rootpath, which I had already done, I looked at something else. I tried to remove the / as well <link rel="stylesheet" href="assets/vendor.css"> intead of  <link rel="stylesheet" href="/assets/vendor.css">. Now everything works.

Thanks again.

**Comment by alexblom** [comment]
No problems. If you upgrade, you should get warnings about this as well :)
