### ISSUE TITLE
Modify the files of the www directory when we change the ember files

### ISSUE THREAD

**Issue by jhonathas** [isleofcode/ember-cordova#194]
Is it possible ember cdv:serve command change the ember-cordova/cordova/www directory files when we modify the ember files? This only happens if I give a build or restart the serve command.

**Comment by alexblom** [comment]
Serve just comes out of a different directory to not mess with prior builds, it currently builds to `ember-cordova/tmp-livereload`. This same directory is cleaned up when you stop serving.

What is your use case so I can better understand?

**Comment by alexblom** [comment]
Going to close this due to inactivity, but please feel free to re-open if you still need support. Come visit us at #e-cordova on the ember-slack as well.
