### ISSUE TITLE
New install cordova:serve not working

### ISSUE THREAD

**Issue by wayne-o** [isleofcode/ember-cordova#197]
```
ember cordova:serve
The specified command cordova:serve is invalid. For available options, see `ember help`.
```

Also - FTR ember `cdv:serve` doesn't work - i.e. the `cdv` shortcut doesn't work at all.

This is with latest ember and all the defaults. Completely fresh install of everything.

w

**Comment by wayne-o** [comment]
I have actually got our app running using the build command though and it's amazing that i got my ember app running on ios in 30 mins! seriously cool.

Just need the serve command to work ;)

**Comment by alexblom** [comment]
Thanks for reporting - I'm going to need to look into this.

**Comment by wayne-o** [comment]
Could it be that 'serve' is missing from here:

https://github.com/isleofcode/ember-cordova/blob/656daed5b0d877e1354b94fb7dd29ee05005690c/lib/commands/cordova.js#L17

?

**Comment by alexblom** [comment]
It won't be from there - though I do need to update that. That block just warns a user if they are using a proxy command we have built in support for, such as build & serve.

I'm generally up to date, what ember-cli version are you on?

**Comment by wayne-o** [comment]
Latest stable I think

**Comment by wayne-o** [comment]
I'll be back at my computer on Sunday.

Are there any guidelines for developing / debugging this library? I'll have
a stab at debugging it if there is :)

**Comment by alexblom** [comment]
I should be around - @alexblom on the ember slack. I'm first going to make sure I'm fully upgraded tonight and see if this manifests - I'm generally up to date though.

Perhaps try emptying out the content of lib/commands/serve & confirm thats even firing, and that service is implemented on commands/index.js in the interim?

**Comment by alexblom** [comment]
I tried to replicate this, and have been unable to on a clean project with latest everything. Am going to need further replication steps.

**Comment by alexblom** [comment]
Going to close this due to inactivity, but please feel free to re-open if you still need support. Come visit us at #e-cordova on the ember-slack as well.
