### ISSUE TITLE
ember-cordova should create dist if it doesn't exist

### ISSUE THREAD

**Issue by Ramblurr** [isleofcode/ember-cordova#199]
If you're starting from a clean checkout, a ember cordova project will not build straight away with `ember cdv:XX` commands, including `prepare` and `platform add`.

It fails with the error "Current working directory is not a Cordova-based project.'

The ACTUAL error is that `dist/` doesn't exist.

It would be nice if:

1) ember-cordova should either create an empty `dist/` for you
2) OR, ember-cordova shows a nicer and more useful error message

**Comment by alexblom** [comment]
Thanks - we should probably handle 1), which I guess is a result of us not building to /dist anymore.

**Comment by alexblom** [comment]
Fixed in 0.3.12.
