### ISSUE TITLE
trying to install ember-cordova (Cannot find module 'uuid' Error: Cannot find module 'uuid')

### ISSUE THREAD

**Issue by abosami2000** [isleofcode/ember-cordova#203]
Hi guys, 

I'm trying to install ember-cordova but there is error 

```
Cannot find module 'uuid'
Error: Cannot find module 'uuid'
```

1- ember new test
2- ember install ember-cordova

**Comment by alexblom** [comment]
Fixed in latest version, thanks for reporting.
