### ISSUE TITLE
Misleading error-message for new root-validations

### ISSUE THREAD

**Issue by doppelreim** [isleofcode/ember-cordova#205]
Disclaimer: I am new to ember, cordova and ember-cordova :)

Using:
```
os: linux x64
node: 6.9.1
ember-cli: 2.9.1
ember-cordova: 0.3.11
```

I created a fresh ember-app, added an application template, and installed ember-cordova.

Following http://embercordova.com/pages/setup_guide, I removed all `{{rootURL}}` from `app/index.html` and set the location-type to `hash`. Also fixed the package-name in `config.xml`.  
Then, added platforms `android` and `browser`.

Both `ember cdv:serve --platform=browser` and `ember cdv:build --platform=android` now abort with the same error-message:

```
Building
ember-cordova: Build Aborted. 
{{rootURL}} or {{baseURL}} in app/index.html has a leading slash. 
This will not work in cordova, and needs to be removed. 
See $docLink for more info. 
You can pass the --force flag to ignore this if youve otherwise handled
Error
```

After a bit of digging, I found that `app/index.html` is not actually the offending file, but `config/environment.js`.  
It contains `rootURL: '/'`. Removing the slash makes the error go away.

I don't know the background of this check. But I guess, it should be mentioned on http://embercordova.com/pages/setup_guide under "Getting Started".  
Is that site powered by the branch `gh-pages` of this repo? If so, I could prepare a little PR with the info.

**Comment by alexblom** [comment]
Thanks for reporting this - updating on the website now. The background is up until the latest release it _was_ app/index.html you modified, and I missed that reference when updating the docs.

**Comment by alexblom** [comment]
Documentation has been updated for this specific error. I've spent the past few days also generally updating the docs, should be out this week.
