### ISSUE TITLE
Can't serve platform browser - strange error-message

### ISSUE THREAD

**Issue by doppelreim** [isleofcode/ember-cordova#206]
...continuing from #205 

I got a new error-message running `ember cdv:serve --platform=browser`:
```
ERROR: Expected a cordova platform to be installed that was not: browser: Not found in config.xml.
You probably need to run ember cdv:platform add browser.
```
That's strange, because I already added the browser platform before. And in fact, trying to add it again yields:
```
Preparing to add platform browser
ERROR ember-cordova with cordova raw 
Platform browser already added.
```
Taking a look inside `config.xml`, I see:
```
<engine name="browser" spec="~4.1.0" />
```
that was added, when I first added the browser platform.  
But the tag is `<engine>`, not `<platform>`. There are `<platform>`-tags for android and ios. But those where there from the start.

When I manually add to `config.xml`
```
<platform name="browser"></platform>
```
then the command runs and I can see the "app" on http://localhost:4200/.  
It contains a script-tag for `cordova.js` - so I assume that something is working?

**Comment by alexblom** [comment]
Thanks. I'm going to need to try and replicate this. In the interim, can I ask what you are using the browser platform for? (e.g. testing plugins /w chrome?)

**Comment by doppelreim** [comment]
I assumed using the browser platform instead of the android emulator or an actual device would allow for faster cycle times. Modifying a file, saving, refreshing, checking - that kind of workflow.

Because a lot of the stack (ember, cordova, ember-cordova) is rather new to me, I assume, I will do a lot of trial and erroring. In that case, fast cycle times help me a lot.

The amended Setup Guide now says, that serving the app via `ember s` is sufficient.  
Going that route would mean, that no cordova-related stuff is available, right? Just trying to grasp the relation of things.

**Comment by alexblom** [comment]
No worries. Yes, in this context you are just looking for:

`ember s`: Usual development flow in Chrome; and
`ember cdv:s`: Also broadcasts to localhost:4200, but allows your on-device development apps to also benefit from live reload.

The --browser platform is a special case for certain plugins that have browser callbacks for testing.

I'm going to close this as I think its answered by using ember s, but please let me know if that is not the case.
