### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by sibijohn72** [isleofcode/ember-cordova#212]
Hi, I am trying to set up a simple ember - cordova app and i am getting this error.... while doing ember cdv:build

```
ERROR: ember-cordova
undefined
Error: ERROR: ember-cordova
undefined
    at Object.module.exports.error (C:\Y\ember-cordova-example-app\node_modules\
ember-cordova\lib\utils\logger.js:21:11)
    at C:\Y\ember-cordova-example-app\node_modules\ember-cordova\lib\commands\bu
ild.js:111:16
    at tryCatch (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_
modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Y\ember-cordova-example-app\node_modules\ember-cordova
\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_m
odules\rsvp\dist\rsvp.js:521:7)
    at publishRejection (C:\Y\ember-cordova-example-app\node_modules\ember-cordo
va\node_modules\rsvp\dist\rsvp.js:456:3)
    at flush (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_mod
ules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by alexblom** [comment]
That is definitely not a useful error message.

Are you passing any particular params to ember cdv:build?

What is the output if you:
```
cd ember-cordova/cordova
cordova build ios
```

**Comment by talhaobject90** [comment]
i am getting apk when executing  
```
 cordova build android,
```

but after installing  the apk , i am getting file  net::ERR_File_NOT_FOUND( FILE:///android_assests/www/index.html) on my phone. 
I guess ember-cordova should generate that file.

**Comment by sibijohn72** [comment]
@talhaobject90 I am getting the same file not found error when I gave ember cordova emulate. I assumed I got that error because I did not build the project even once before giving the emulate command.

**Comment by sibijohn72** [comment]
@alexblom I am actually building for android. I'll post the console log for the commands you gave soon. 

No,  I did not give any additional parameters.

**Comment by sibijohn72** [comment]
@alexblom The build is successful for the directory you gave but i still dont understand why ember cdv:build results in the above error.

**Comment by sibijohn72** [comment]
@alexblom Even i am getting the same issue when i run the emulate command. :ERR_File_NOT_FOUND( FILE:///android_assests/www/index.html)

Any suggestions?

**Comment by sibijohn72** [comment]
@alexblom 
1. Yes, ember build is successful.

2. There is no index.html file in "ember-cordova/cordova/" and also the "www" folder is empty.

**Comment by alexblom** [comment]
Thanks. Can you confirm you are running the following commands:

`ember cdv:platform add android`
`ember cdv:build --platform=android`

We do need a better error, but thusfar the only way I've been able to replicate the error you are seeing is by trigger a build for a platform that does not exist.

In lieu, is there a shell project you have with this issue I can copy?

**Comment by BinaryCitizen** [comment]
I fixed this by deleting the platform folders `ember-cordova/cordova/platforms/<android>, <ios>`

**Comment by sibijohn72** [comment]
@BinaryCitizen  Same here. I had to use the remove command to remove the installed android platform and then reinstall it. I actually had to repeat the process a few times, before it started workin. I guess its because the platform didn't get installed properly. However a more specific error message would surely be helpful. Cheers!

**Comment by alexblom** [comment]
Should be fixed in latest release. Please re-open if that is not the case.
