### ISSUE TITLE
Pass environment variable to build

### ISSUE THREAD

**Issue by 0000marcell** [isleofcode/ember-cordova#213]
Sorry if this was already mentioned before, but i'm not being able to pass the environment variable to the build task, i wanna configure locationType based on the environment.

is there any other way to identify if i'm running the build in cordova context, i would be happy to add this info to the docs if thats the case.

**Comment by charlieridley** [comment]
@0000marcell Having the same issue. Did you find a solution?

**Comment by 0000marcell** [comment]
@charlieridley no, but i realize its better (at least in case) to keep the cordova project in a separate branch, the mobile experience is very different

**Comment by charlieridley** [comment]
Ok, I'm sharing the code base so need to do this, but I actually have found a solution. For some reason the build passes undefined into the environment.js function a few times and then it does actually call with the desired environment. So I just make sure the defaults satisfy cordova and then override them in my development config like this:

```
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'sparkplug-client',
    environment: environment,
    locationType: 'hash',
    EmberENV: {
      FEATURES: {
        
      }
    },

    APP: {
    }
  };

  if (environment === 'development-cordova') {
    ENV.locationType = 'hash';
    ENV.host = 'http://10.0.1.2:5000';
    ENV.rootURL = '';
    ENV.cordova = {
      reloadUrl: 'http://10.0.1.2:49152/'
    }
  }

  if (environment === 'development') {
    ENV.rootURL = '/';
    ENV.locationType = 'auto';
    ENV.APP.LOG_TRANSITIONS = true;
  }
.
.
.

```

**Comment by 0000marcell** [comment]
@charlieridley thx, im gonna test it out later, but im pretty sure i've tried that, in my case the log is a bunch of undefined and then test, which ember version are you using ?

**Comment by charlieridley** [comment]
I'm up to date on 2.10 for ember, ED and ember-cli.
