### ISSUE TITLE
index.html not found

### ISSUE THREAD

**Issue by sibijohn72** [isleofcode/ember-cordova#214]
Hi,

I am not able to build using the ember cdv:build command (issue #212 ) so i ran ember cordova emulate which runs and gives an apk file but when the app opens up in the emulator it says index.html is not found. I have removed all references to {{rootURL}} from index.html and also remove the leading slash from rootURL. locationType is also set to hash.

**Comment by alexblom** [comment]
I'm going to close this in favour of #212, the issues you are describing are definitely related.
