### ISSUE TITLE
Environment not being set

### ISSUE THREAD

**Issue by charlieridley** [isleofcode/ember-cordova#219]
I'm running `ember cdv:build --platform=ios --environment=development-cordova` but the environment does seem to be set.

I put `console.log('Environment is ' + environment);` in my environment.js and output is `Environment is undefined`

**Comment by charlieridley** [comment]
I found a temporary solution and posted here:

https://github.com/isleofcode/ember-cordova/issues/213

It looks like undefined gets passed to environment.js a couple of times before passing the actual environment.

**Comment by alexblom** [comment]
Thanks for reporting - I've put this next on my plate to dig in to.

**Comment by reidab** [comment]
From the looks of things, the problems here stem from not passing the environment when building the environment for validation. I'll toss a PR up momentarily.
