### ISSUE TITLE
Request denied for security

### ISSUE THREAD

**Issue by jakope** [isleofcode/ember-cordova#239]
I'm sure, it's my mistake and not an issue. But hopefully someone could help me please. 

The signed android App in the Play Store doesn't allow any requests (notify comes up, request is denied for security) or the request is cancelled. When I install the debug.apk everything works fine.

Does anybody know's this?

Thank you

**Comment by alexblom** [comment]
Hey - this is definitely not common. Can you advise me on exactly what error you are seeing?

**Comment by kylemellander** [comment]
I'm not sure if this is the same issue.  But when building for iOS, it seems to making CORS requests for the resources (which it shouldn't).  I am trying to track this down, but I think it might be ember-cordova.

**Comment by alexblom** [comment]
Going to close this due to inactivity, but please reopen if you still have problems.
