### ISSUE TITLE
Expected a cordova platform to be installed that was not: android:

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#244]
I already did `ember cdv:platform add android` and still complaining, after version upgrade.

**Comment by v3ss0n** [comment]
`Expected a cordova platform to be installed that was not: android: Not found in fetch.json. You probably need to run ember cdv:platform add android.
`

**Comment by alexblom** [comment]
Thanks for reporting. Heading in to ember-cordova/cordova/platforms, can you confirm the platform exists?

You may need to remove the android folder, and re-add the platform.

**Comment by v3ss0n** [comment]
thanks @alexblom  after nuking everything it worked.
