### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#245]
I keep visiting back to this issue, because I keep facing it with every new project I create.

## Environment
- ember-cli: 2.10.0
- node: 6.9.2
- os: darwin x64
- crodova: 6.4.0
  - android = "~6.0.0"
  - cordova-plugin-crosswalk-webview ="~2.2.0"

## Steps executed
- `ember new cdvDiag`
- `cd cdvDiag/`
- `ember install ember-cordova --name=diag --cordovaid=com.XXXXXXX.diag `
- `ember cdv:platform add android`
- `ember g route application`
- `ember cdv:build --platform android`

## Error
```
:validateSigningArmv7Debug
:packageArmv7Debug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageArmv7Debug'.
 > java.io.FileNotFoundException: /Users/XXXXXXX/projects/tmp/cdvDiag/ember-cordova/cordova/platforms/android/build/intermediates/assets/armv7/debug/www/assets (Is a directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by alexblom** [comment]
So far I've not been able to replicate, even following these steps on a fresh project. Can you confirm your env is setup as documented here: https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html?

Otherwise shoot me a DM on slack and a quick hero may be in order. I'd like to fix this, but can't make it happen.

**Comment by hashg** [comment]
I removed xwalk and re installed android with old webview it started working without any complains.
Let me try to build a new project and commit the project, so that you can clone it and see if you can reproduce the issue.

**Comment by hashg** [comment]
Not reproducible anymore. Will reopen when I have a reproducible repo uploaded online.
