### ISSUE TITLE
Cannot Locate ember-resolver For iOS

### ISSUE THREAD

**Issue by shoxter** [isleofcode/ember-cordova#246]
So we've been running our app with this plugin on android for the better part of a year now. We just started trying to deploy it to iOS, I set up all the certificates, provisioning profile, etc for Xcode, but when I deploy our app to a device or use the ember cordova command to deploy it to a simulator, I get a white screen.

After investigating, this is the error we're getting: `could not find module 'ember-resolver' imported from 'my-app/resolver'`

This error doesn't happen for android or a local `ember serve` and I've tried a few things to fix it with no luck -- any idea what could be causing this?

**Comment by alexblom** [comment]
That reads closer to an issue with your ember build. Are you having any issues with standard `ember build/serve`?

**Comment by shoxter** [comment]
@alexblom I have no issues with anything but trying to run it for iOS in either a simulator or deploying to device.

**Comment by alexblom** [comment]
Going to close this, as we just hero'd and traced the issue to being general to Webkit browsers vs Cordova.
