### ISSUE TITLE
Deprecation Warning: ember-cli/ext/promise is deprecated, use rsvp instead

### ISSUE THREAD

**Issue by cooperjbrandon** [isleofcode/ember-cordova#251]
After installing ember-cordova, and then running any `ember` command, 15 deprecation warnings about the `ember-cli/ext/promise` library occur.

It occurs for each file in the `lib/tasks` directory from this repo.

Example deprecation warning:
```
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/my_app/node_modules/ember-cordova/lib/tasks/validate/cordova-installed.js:4:23)
```

Note this occurs both on node version 4 (4.7.3) and version 6 (6.9.5)

**Comment by cooperjbrandon** [comment]
Ahh looks like it was because I was on the beta version of Ember-cli (v2.12.0-beta.1), when the  latest stable release is v2.11.0

**Comment by Senthe** [comment]
It still happens to me with Ember CLI 2.12.1, which is the stable version right now. Please reopen.

**Comment by cooperjbrandon** [comment]
👍
