### ISSUE TITLE
platform.device is an empty object

### ISSUE THREAD

**Issue by tavosansal** [isleofcode/ember-cordova#271]
Injecting the platform service and doing `this.get('platform.device')` results in an empty object.
I believe the culprit is here https://github.com/isleofcode/ember-cordova/blob/5946eb2c4fd7148c3b5e2ec2dbef844ff57150d3/addon/services/ember-cordova/platform.js#L114

I have a feeling that when this computed is returned, the device cordova plugin has not loaded yet causing this to be undefined.
Here is a screenshot:

![web_inspector_ _simulator_ _coschedule_ _192_168_1_16](https://cloud.githubusercontent.com/assets/5883244/23187975/8d46dd02-f852-11e6-806b-43a63ef67a07.png)

This inspecting with Safari running on physical device.

**Comment by alexblom** [comment]
I'll ensure it is listed in the documentation - do you have `cordova plugin add cordova-plugin-device` installed? If the device is undefined, that would be why.

**Comment by tavosansal** [comment]
@alexblom yes, that plugin is installed `<plugin name="cordova-plugin-device" spec="~1.1.3"/>`
I am using embercordova v0.4.2...this started breaking for me when I updated from v0.3.12

**Comment by alexblom** [comment]
Ok. Does your raw (not from the service) window.device ever resolve, or does even that remain undefined once the app has fully loaded?

**Comment by tavosansal** [comment]
window.device does resolve when the app is loaded. I changed my references to that in my code and have had no issues. Wondering if this is an Ember CP behaviour. Since the CP is not observing anything, maybe the first time that it was computed `window.device` was undefined. If you get the CP later, it would just give you the cached value which would be `undefined`. Not sure I am correct but it is a theory.

**Comment by alexblom** [comment]
So far I've been having trouble replicating on the latest release. I can see a scenario where device.platform is being called before the `deviceready` event.

Before I go ahead and make any chances, can you perhaps confirm that this is only happening when using the service before deviceready?

**Comment by tavosansal** [comment]
So this is what I have 
routes/application.js
```
if (this.get('platform.isIOS') || this.get('platform.isAndroid')) {
      this.get('cordova').ready()
        .then(() => {
          this.setIOSStatusBar();
          this.changeAndroidColor();
          this.mobileAppLoadedAnalytics();
        });
    }
```

And in the `mobileAppLoadedAnalytics`: 
```
mobileAppLoadedAnalytics() {
    if (ENV.environment === 'production') {
      const requestData = {
        key: 'performance-mobile-loaded',
        data: {
          model: this.get('platform.device.model'),
          platform: this.get('platform.device.platform'),
          version: this.get('platform.device.version'),
          manufacturer: this.get('platform.device.manufacturer'),
        },
      };
     ...
    }
  },
```

So in theory that function should only run on cordova ready (unless I am doing it wrong). This is the only way that the `mobileAppLoadedAnalytics` function gets invoked. I hope this helps.

**Comment by alexblom** [comment]
Thanks for the example. You will actually need to switch this block around, and its unclear we will update the docs:

```
if (this.get('platform.isIOS') || this.get('platform.isAndroid')) {
      this.get('cordova').ready()
        .then(() => {
          this.setIOSStatusBar();
          this.changeAndroidColor();
          this.mobileAppLoadedAnalytics();
        });
    }
```

becomes:

```
this.get('cordova.ready()
  .then(() => {
    if (this.get('platform.isIOS') || this.get('platform.isAndroid')) {
        this.setIOSStatusBar();
        this.changeAndroidColor();
        this.mobileAppLoadedAnalytics();
      });
  }
```

The device information is not available until the `deviceready` event.

**Comment by tavosansal** [comment]
I will give this a try and report back. Thanks.

**Comment by alexblom** [comment]
Just wanted to follow up - did this work out for you?

**Comment by tavosansal** [comment]
It did. Sorry for not getting back. I forgot about it.

Thanks.
