### ISSUE TITLE
Script tag for cordova.js is missing

### ISSUE THREAD

**Issue by xcskier56** [isleofcode/ember-cordova#272]
Not sure if this is documented somewhere, but I cannot seem to get `ember cdv:build` or ember `cdv:s` to include `<script src=”cordova.js"></script>` in my index.html file.

I've added a log statement in `contentFor()` in `index.js` and at no point does `this.project.targetIsCordova` ever become defined. 

When I remove `if (this.project.targetIsCordova)` and just leave the conditional on the body, then the cordova.js file is correctly included in the index.html

Should I be setting `project.targetIsCordova = true` somewhere in my config?

**Comment by xcskier56** [comment]
Ember 2.10, ember-cordova 0.4.4

**Comment by xcskier56** [comment]
Solved. It was a simple error that was introduced when I switched from using a brocfile to ember-cli-build.js quite a while ago

My apologies for taking up your time, and appreciate your help.

**Comment by alexblom** [comment]
No worries - I'd just gotten a build running and was going to ask for more details. Glad it's all working for you now.
