### ISSUE TITLE
Installation Error - spawn undefined ENOENT

### ISSUE THREAD

**Issue by aalasolutions** [isleofcode/ember-cordova#273]
Hi, 

I am trying to install the addon and I am getting `spawn undefined ENOENT` errors. I have tried installing other addons they are are installed, and I also tried from couple of different internet connections. 

Here is part of log

```
  ember-cli:command initialize: name: install, name: +220ms
  ember-cli:platform-checker: { version: 'v6.9.1', isValid: true, isTested: true, isDeprecated: false } +170ms
  ember-cli:cli command: install +1ms
  ember-cli:testing cli: command.validateAndRun +5ms
  leek enqueue eventType:appview silent:undefined payload:{ name: 'ember ', message: 'install' } +5ms
  leek:get-version getVersion platform:win32 release:10.0.14393 output:  win32 10.0.14393 +45ms
  leek:provider getAppViewObject { v: 1, t: 'appview', aip: 1, tid: 'UA-49225444-1', cid: 'ember-clic6e9b8e1e22db5719bc1336091aee5c9', an: 'ember-cli', av: '2.10.1', cd: 'install', cd1: ' win32 10.0.14393', cd2: 'v6.9.1', qt: 0, z: 1487830129508 } +2ms
  leek:provider eventType: appview url: undefined +6ms
  leek http 'https://google-analytics.com/collect?v=1&t=appview&aip=1&tid=UA-49225444-1&cid=ember-clic6e9b8e1e22db5719bc1336091aee5c9&an=ember-cli&av=2.10.1&cd=install&cd1=%20win32%2010.0.14393&cd2=v6.9.1&qt=0&z=1487830129508' +3ms
spawn undefined ENOENT
```

**Comment by alexblom** [comment]
This is happening after an `ember install ember-cordova`

Can you provide me a little more env info please? (ember/ember-cli/node v's and os).

**Comment by aalasolutions** [comment]
I have run these two commands

```
ember new ember-cordova 
cd ember-cordova
ember install ember-cordova
```
Part of debug info is mentioned in my first message

Version / Node versions 
```
$ ember --version
ember-cli: 2.10.1
node: 6.9.1
os: win32 x64
```


Debug Info
```
DEBUG: -------------------------------
DEBUG: Ember      : 2.10.2
DEBUG: Ember Data : 2.11.1
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
Ember Inspector Active
```

**Comment by alexblom** [comment]
Thanks. It could be Windows related - I'll need to run a test case on my Windows machine when I'm at home.

**Comment by aalasolutions** [comment]
@alexblom Any updates on this?

**Comment by alexblom** [comment]
Was getting sidetracked while fixing validators & plugin tests. The former is now merged, the latter has a pattern and is being fixed elsewhere. 

I actually started re-setting up my home Windows env over the weekend. It'll probably take me a few days as I honestly don't use it for development (only gaming :)).

**Comment by aalasolutions** [comment]
:D love games, Well, I am trying again, was having NPM 3x. just updated it to 4.4 tried in old folder got same error. Right now creating new ember project.

**Comment by alexblom** [comment]
Are you on the ember-slack. I can possibly diagnose the issue fast by seeing it in screen hero

**Comment by aalasolutions** [comment]
Strange, it just worked out in new project. Just thinking to make a clone of it 🤣  so it wont get buggy again

**Comment by alexblom** [comment]
Great to hear. Can you let me know when you've successfully run a build so we can close the issue?

**Comment by aalasolutions** [comment]
Each time it gave me some error, a configuration and I keep on updating it. I have added Android Platform, but when I do run `ember cdv:serve` i get the following error

WARNING: ember-cordova

Your ember-cordova/cordova/config.xml file has set thefollowing flag:
        <allow-navigation href="*" />
This is necessary for device live-reload to work,
but is unsafe and should not be used in production.
```

ERROR: ember-cordova
Expected a cordova platform to be installed that was not: ios: Not found in fetch.json. You probably need to run ember cdv:platform add ios.
Error: ERROR: ember-cordova
Expected a cordova platform to be installed that was not: ios: Not found in fetch.json. You probably need to run ember cdv:platform add ios.
    at Object.error (D:\xampp\htdocs\ember\cordova\node_modules\ember-cordova\lib\utils\logger.js:21:11)
    at D:\xampp\htdocs\ember\cordova\node_modules\ember-cordova\lib\commands\serve.js:148:14
    at tryCatch (D:\xampp\htdocs\ember\cordova\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (D:\xampp\htdocs\ember\cordova\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (D:\xampp\htdocs\ember\cordova\node_modules\rsvp\dist\rsvp.js:522:7)
    at publishRejection (D:\xampp\htdocs\ember\cordova\node_modules\rsvp\dist\rsvp.js:457:3)
    at flush (D:\xampp\htdocs\ember\cordova\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I tried to install IOS that got installed, but I got error for xCode. Removed that. 

So kinda stuck over here

**Comment by alexblom** [comment]
The default build platform is iOS, and in general iOS can not be built on Windows machines.

You need to run `ember cdv:build --platform=android` or change the default preference (modify .ember-cli  and set platform to 'android')

**Comment by aalasolutions** [comment]
Hi Alex, looks like everythings is working for now.


closing
