### ISSUE TITLE
ember cdv:serve not including splash plugin

### ISSUE THREAD

**Issue by drewcovi** [isleofcode/ember-cordova#276]
`
Error: Attempting to inject an unknown injection: 'service:ember-cordova/splash'
`
This message currently shows up when running ember cdv:serve.  I'm following direction from http://embercordova.com/pages/workflow/icon_splash_management. My understanding is this environment should have access to all plugins etc:

> Live reload takes the standard ember serve live reload behaviour to apps running on your phone. Apps running in this context maintain access to Cordova plugins.

http://embercordova.com/pages/workflow/livereload

Any short-term fix available?

**Comment by alexblom** [comment]
If you are getting an undefined service error, it's not yet related to the cordova plugins.  It looks like we need to do a documentation update. You'll need to `ember install ember-cordova-splash` to use the service. 

I'll  leave this open until we fix the docs.

**Comment by drewcovi** [comment]
@alexblom worth noting: I'm not getting any issues when I actually deploy to a native device. only when using cdv:serve

**Comment by alexblom** [comment]
Thanks for bringing this up - it looks like we were not installing the cordova-plugin for this addon. Version 0.1.2 of ember-cordova-splash should resolve this issue. Please re-open if thats not the case.
