### ISSUE TITLE
`afterPrepare` hook is not fired by `ember cdv:build`

### ISSUE THREAD

**Issue by rmehner** [isleofcode/ember-cordova#284]
Hey there,

I think this is either a misunderstanding or an actual bug :) I've expected `afterPrepare` to be fired when `ember cdv:build` runs, as the documentation states:

> Use ember-cordova hooks for build-time customization, cleanup or warnings. These follow a similar pattern to Cordova’s hooks, but are specific to ember-cordova builds.
– http://embercordova.com/pages/workflow/hooks

and `afterPrepare` in fact fires during a cordova build according to the [cordova hooks documentation](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html) which is also easy to verify if you add something like this to your `config.xml`

```xml
<hook type="after_prepare" src="../../bin/afterPrepare.js" />
```

My understanding (which, as I've said, might be wrong) was that ember cordova hooks are modeled by the actual cordova hooks and have a similar behaviour. What's your stance on this? Would a PR that also fires `afterPrepare` before a build be merged? Or are these two hook types not related to each other?

Thank you for your work and have a great day!

**Comment by alexblom** [comment]
That documentation definitely needs a cleanup. Right now, our hooks work as following:

- beforeBuild/afterBuild fires on `cdv:build` and `cdv:serve` events;
- beforePrepare/afterPrepare fires on `cdv:prepare` events;

So much as a prepare is part of a cordova build, we don't fire ember-cordova prepare events. The docs need to be updated to state our hooks are functionally modeled from cordova hooks, but don't fire in the same instances.

I'm also figuring `cdv:prepare` will further deviate from `cordova prepare` (i.e.  ember app setup) - and have been debating renaming it to `cdv:install` or `cdv:setup`.

Hope the context helps. I'm very open to exposing cordova-prepare hooks in the build process (especially after renaming), but I'd also want to grok the use case.

**Comment by rmehner** [comment]
Thank you for the clarification. So it's definitely "just" a documentation issue (or me, not understanding the documentation right :)) But that bit about when which events fire would definitely be good to have on http://embercordova.com/pages/workflow/hooks (like [Cordova's hook documentation](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html#introduction)) and with a note that this hooks are not really related, just share the same mental model :)

Anyway, to give you the context of my use case (and I still haven't found a satisfactory answer to this problem):

I have two separate builds of the app (staging and production) which both speak to different backends, but are essentially the same app. The Google Play Store process with betas doesn't work really well for that, as I'd need to have both apps on the devices, staging updating itself quite more often. To achieve that, I need to change certain values in the `config.xml` based on the environment. Initially I thought that I need to change the `AndroidManifest.xml` and others, but I guess I'll just go with the `config.xml`, so `beforeBuild` should be fine.

Obviously this is not a really good solution, especially if run in non-CI builds, as it is going to overwrite config.xml all the time, but this is entirely unrelated to `ember-cordova`.

Thanks again!
