### ISSUE TITLE
Icon management docs

### ISSUE THREAD

**Issue by Ramblurr** [isleofcode/ember-cordova#29]
Migrating from ember-cli-cordova, where I managed the icon myself with cordova-icon, how do I take advantage of the auto generation in ember-cordova?

**Comment by AlexBlom** [comment]
@runspired is still working on fixing and implementing this. Expect an update by next week.

**Comment by Ramblurr** [comment]
Any updates here? Icon and splash screens are broken, even when I run the cordova-{icon,splash} commands  in ember-cordova/cordova.

**Comment by gilest** [comment]
Hey @Ramblurr I'm not sure about the auto-generation but I have my splash screen set manually and it's being included in the build correctly.

Files are located at:
```
ember-cordova/cordova/res/Default-Landscape.png
ember-cordova/cordova/res/Default-Landscape@2x.png
```

Platform block for ios in `ember-cordova/cordova/config.xml`:
```
<platform name="ios">
    <allow-intent href="itms:*" />
    <allow-intent href="itms-apps:*" />
    <splash height="768" src="res/Default-Landscape.png" width="1024" />
    <splash height="1536" src="res/Default-Landscape@2x.png" width="2048" />
    <splash height="1242" src="res/Default-Landscape@2x.png" width="2208" />
</platform>
```

Hope this helps while the docs are being worked on.

**Comment by Ramblurr** [comment]
@gilest thanks. Should the files be in `ember-cordova/cordova/res/` or in `ember-cordova/cordova/res/ios` (for the ios platform)?

**Comment by Ramblurr** [comment]
Ah, I think I found the source of confusion. I assumed ember-cordova was referring to the splash generation util (https://github.com/AlexDisler/cordova-splash), but I gather instead you're referring to the splashscreen plugin (https://github.com/apache/cordova-plugin-splashscreen)

**Comment by gilest** [comment]
Hey @Ramblurr I've been running `cordova-icon` from the `ember-cordova/cordova` dir with no issues. Also using the iOS platform.

Maybe try removing and re-adding the iOS platform.

**Comment by AlexBlom** [comment]
Finally can close this, as I've added icon management to the latest release. See: https://github.com/isleofcode/ember-cordova/blob/master/docs/services/icons.md

**Comment by Ramblurr** [comment]
Awesome @AlexBlom ! That's great. I suppose it is intended to ignore the generated icons in git?

Also, is there a similar generator for the splash screens?

**Comment by AlexBlom** [comment]
It was, but perhaps we should reconsider or just add the generator to prepare so nobody gets caught out.

Re: splash yes, thats my current programming task :) Just thought I'd push out icons as they were done, and splash in the coming days. 

All I've got left with splash is resizing to different scales (e.g. 1:2 vs 1:3) and that item is completed too.
