### ISSUE TITLE
Addon is missing a dummy app for testing

### ISSUE THREAD

**Issue by villander** [isleofcode/ember-cordova#30]
➜  ember-cordova git:(master) ember -v
version: 2.3.0
node: 4.0.0
os: darwin x64
➜  ember-cordova git:(master) node -v
v4.0.0
➜  ember-cordova git:(master) npm -v
3.8.6
➜  ember-cordova git:(master) 

````
➜  ember-cordova git:(master) ember s
version: 2.3.0
DEPRECATION: this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: qunit-bdd]
broccoli-funnel does not support `files:` option with globs, please use `include:` instead
DEPRECATION: this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: qunit-bdd]
Attempting to watch missing directory: tests/dummy/app
Error: Attempting to watch missing directory: tests/dummy/app
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/flama/Projects/ember-cordova/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/flama/Projects/ember-cordova/node_modules/broccoli/lib/builder.js:94:35
    at lib$rsvp$$internal$$tryCatch (/Users/flama/Projects/ember-cordova/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/flama/Projects/ember-cordova/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/flama/Projects/ember-cordova/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/flama/Projects/ember-cordova/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

**Comment by runspired** [comment]
There is no error in your trace above...

**Comment by villander** [comment]
@runspired what the error? Help me!

**Comment by runspired** [comment]
@villander misread this initially as you were having trouble in a consuming app, not trying to mess with the lib itself, sorry!

The error here is that there is no `dummy app`, which "sorta makes sense" (I don't actually think it does) because there isn't an Ember code to test here, really.  It's mostly cordova integration code.

@AlexBlom guessing this goes into the "we need a better test story" column.

**Comment by villander** [comment]
@runspired thanks I knew it was something related to `dummy app`, i should have communicated better haha.

Anyway we need a `dummy` to test and ensure the quality of` addon` without having another project for this. What do you think @AlexBlom ?

**Comment by AlexBlom** [comment]
I'd agree having a dummy app for the test story makes sense. In general, I think the test story is weak. I'm just coming off a crazy sprint and can now dedicate regular time here again.

Fixing testing is something I'm doing this week. Will keep this issue updated, if you have any time to help out lmk.

**Comment by AlexBlom** [comment]
Just to update, I'll be pushing a testing branch that resolves this.

**Comment by villander** [comment]
Thanks @AlexBlom  💃

**Comment by villander** [comment]
@alexblom i'm up-to-date with branch `master` of this repo. and still not have a `dummy app`
