### ISSUE TITLE
To Document : Platform service

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#327]
Need to document how to correctly inject platform service with latest relase.
`platform: Ember.inject.service("ember-cordova/platform"),`

**Comment by alexblom** [comment]
That has been in the production docs for a while, unless I am missing something http://embercordova.com/pages/service_platform. 

It was also in the 0.44/0.45 release notes, which may be useful to follow. I tend to keep those updated with changes and deprecations:
https://github.com/isleofcode/ember-cordova/releases/tag/0.4.4
https://github.com/isleofcode/ember-cordova/releases/tag/0.4.5

**Comment by v3ss0n** [comment]
I can't do   lookup('service:ember-cordova/platform');
and what it does actually ?
