### ISSUE TITLE
--force fails to force past hash check

### ISSUE THREAD

**Issue by Kilowhisky** [isleofcode/ember-cordova#355]
My application uses content source that is not the ember app. So i don't need to use 'hash' or any of the regular ember build checks. 

```<content src="https://myapplivelocation.com" />```

So when i build using the force flag it still refuses to build unless i change my code. 

```ember cdv:build --platform=android --force```

```
EmberCordovaError: Validation error(s)

* config/environment.js: Cordova applications require:
`ENV.locationType = 'hash';
```

**Comment by alexblom** [comment]
Thanks for reporting this - have managed to replicate.
