### ISSUE TITLE
Node 8 compatibility

### ISSUE THREAD

**Issue by bjornharrtell** [isleofcode/ember-cordova#357]
I find `^4.5 || 6.* || 7.*` in `package.json` disallowing use under Node 8. Limited tests seems to indicate it works though.

**Comment by alexblom** [comment]
Thanks for the report. I'll give 8 a better test before updating but there is no reason it shouldn't work.

**Comment by alexblom** [comment]
Node 8 compatibility is no mentioned in package, thanks for bringing this up!
