### ISSUE TITLE
Strange affair with locationType and force flag. It's not a problem of mine.

### ISSUE THREAD

**Issue by johnunclesam** [isleofcode/ember-cordova#362]
I'm with newest `ember-cli 2.14.2` and the latest `ember-cordova`, nodejs 8.3.0, npm 5.3.0.

Anyway with a new project, standard I have this issue:

```
$ ember cdv:build --platform=android --environment=production
ember-cordova: Building app
WARNING: ember-cordova
* config/environment.js: Cordova applications require:
`ENV.locationType = 'hash';
You have passed the --force flag, so continuing
```

I already changed `config/environment.js` as stated here: http://embercordova.com/pages/workflow/project_setup

And I never used the `--force` flag.

Is everything ok?

**Comment by alexblom** [comment]
Thanks for reporting - the fix has been implemented in https://github.com/isleofcode/ember-cordova/pull/363
