### ISSUE TITLE
Sample or Reference app required

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#41]
It would be nice to have a sample app, which kind of will help early adopters. It should atleast cover basic features provided by ember-cordova.
Ember-Cli-Cordova creator had done this - https://vimeo.com/107885050

I have been facing bunch of issues. One of it is how to getride of splash screen.

Even after this it is not loading my app. still stuck at splash screen.

```
// app/routes/application.js
import Ember from 'ember';
import SplashscreenMixin from 'ember-cordova/mixins/device/splashscreen';

const { Route } = Ember;

export default Route.extend(SplashscreenMixin, {
    beforeModel() {
      this.get('splashscreen').hide();
    },

    model() {
      return ['red'];
    }
});
```

**Comment by alexblom** [comment]
Take a look here for a very early example: https://github.com/isleofcode/super-rentals-cordova

We'll work towards something more comprehensive.
