### ISSUE TITLE
Is there a discuss channel for using ember cordova?

### ISSUE THREAD

**Issue by zxcware** [isleofcode/ember-cordova#43]
Hi guys,

I am trying to set up the super-rentals project from emberjs guide(https://guides.emberjs.com/v2.5.0/tutorial/ember-cli/) with ember-cordova. After following the instructions on the README, I simply got a blank page in an ios simulator. I am new to ember and cordova. Is there a discuss channel or meetup where newb can seek for helps?

Thanks,
Xiong

**Comment by AlexBlom** [comment]
I don't think so yet, but if you pop in mobile we're generally around. Feel free to open an Issue with as well and happy to help.
