### ISSUE TITLE
Error when running ember cdv platform add android

### ISSUE THREAD

**Issue by valk** [isleofcode/ember-cordova#44]
Followed the instructions, also I have this in my package.json and bower.json:

```sh
  "name": "com.company.Name",
```

but getting this, not sure why:

```sh
ember cdv platform add android
Running 'cordova platform add android'
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name
File: /bin/sh
Command failed: cordova platform add android
Error: Command failed: cordova platform add android
    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at /home/user/my-ember-cordova/node_modules/ember-cordova/lib/tasks/bash.js:23:7
    at lib$rsvp$$internal$$initializePromise (/home/user/my-ember-cordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/home/user/my-ember-cordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/home/user/my-ember-cordova/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.run (/home/user/my-ember-cordova/node_modules/ember-cordova/lib/tasks/bash.js:17:12)
    at Class.module.exports.Task.extend.run (/home/user/my-ember-cordova/node_modules/ember-cordova/lib/tasks/cordova.js:21:8)
    at Class.module.exports.run (/home/user/my-ember-cordova/node_modules/ember-cordova/lib/commands/cordova.js:54:27)
    at Class.module.exports.validateAndRun (/home/user/my-ember-cordova/node_modules/ember-cordova/lib/commands/cordova.js:44:17)
```

**Comment by thijsvdanker** [comment]
Did your app name have a dash (-) or underscore in the name before you changed it to `com.company.Name`?
I had that same issue because of it.

I think you need to change the widget id in the generated `/path/to/project/ember-cordova/cordova/config.xml`
to `com.company.Name` as well (or to something that makes more sense to your own app).

**Comment by valk** [comment]
@thijsvdanker I had dashes before indeed.

Now started anew with this name "mcordova", then renamed it to com.myapp.Mobile but still getting the same error. (Tried other combinations with underscores, capital / noncapital names like com.myapp.mobile etc.)

**Comment by thijsvdanker** [comment]
You did change the config.xml as well? (it was a while ago for me, so I'm not 100% sure what my steps were to fix it).

You could rule out the ember bit by running `cordova platform add android` directory from the `ember-cordova/cordova/` directory.

**Comment by valk** [comment]
Ok, as @thijsvdanker  suggested, I did this:

```sh
cd ember-cordova/cordova
edit config.xml
```
The only thing that needed to be changed is the id of the <widget> tag with com.myapp.Mobile, so:

```xml
<widget id="com.myapp.Mobile" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
```

Then I ran:

```sh
ember cdv platform add android
```

and got success:


```sh
Running 'cordova platform add android'
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.myapp.Mobile
	Name: mcordova
	Activity: MainActivity
	Android target: android-23
Android project created with cordova-android@5.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Thanks for the help @thijsvdanker !

**Comment by thijsvdanker** [comment]
You're welcome :)

**Comment by v3ss0n** [comment]
@thijsvdanker  i had finished this step but when actually built using:
ember cordova:build , it is successfully linked with www and dist
buth when ember cordova emulate , it the debug shows none of the css/js files are found.
help pls?

**Comment by thijsvdanker** [comment]
@v3ss0n What do you mean with none of the css/js? Not the cordova ones?
Could you post the output of `ember cordova emulate` here?

**Comment by v3ss0n** [comment]
thanks its working now , just need to change locationType to hash! thanks again!
