### ISSUE TITLE
exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova global code - index.html:1:127

### ISSUE THREAD

**Issue by zxcware** [isleofcode/ember-cordova#46]
I checked out the emberjs example super-rentals app: https://github.com/emberjs/super-rentals. After installing all of the dependencies, I opened 2 tabs:

### In tab1

- I ran command: ember cdv:serve
- Checking in the browser with url: localhost:4200, the website showed up correctly

### In tab2

- I ran command: ember cdv:buid && ember cdv emulate ios
- The simulator was launched but the app showed a blank screen, 'ember cdv:serve' still running in tab1

I hook up the safari browser of my notebook to the app running in simulator, its console tap displaying information "exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova global code - index.html:1:127".

### Questions

1. Did I miss any steps?
2. Was the information telling the reason why the app can't show up in ios simulator?

**Comment by AlexBlom** [comment]
If you run a standard ember cdv:build without liveReload, is that successful?

**Comment by zxcware** [comment]
@AlexBlom Do you mean not running 'ember cdv:serve' in tab1? I felt I didn't do anything for liveReload. In my idea: Running ember cdv:serve launches a server, the simulator will then be able to fetch the content from the server and renders it out.

**Comment by zxcware** [comment]
@AlexBlom What's the best way to reach you? email or twitter?

**Comment by AlexBlom** [comment]
email or ember-slack (@alexblom there too). Happy to do a quick hero to debug this.

By the question, I'm asking if you just run:

```
ember cdv:build
ember cordova run ios
```

Does the app work as expected? (e.g. is your issue that all builds are broken, or live reload builds are broken).

**Comment by zxcware** [comment]
No. just running those commands didn't work. I tried it with and without another tab running 'ember serve', both resulting in a white blank screen after the 'cordova robot' splash screen.

My issue is: following the instructions and applying ember-cordova to emberjs example super-rentals app: https://github.com/emberjs/super-rentals doesn't work. Not sure if it can be marked as 'some build is broken'. 

Once we make it work, it can be an example app for ember-cordova. I'll set up a git public repository of my sample codes and we'll work together to fix it. 

See you on slack.

**Comment by AmilKey** [comment]
any updates here?

**Comment by AlexBlom** [comment]
@AmilKey: Responding to you in your issue.

@zxcware: I just tried to download the super-rentals app (master branch) so you can compare.

I can see it when I run ember server, but builds seem to be generically producing a white screen (ember build --env=development, ember build --env=production). 

Can you confirm normal ember builds are working?

In general, for live reload to be working we need to be in a state where:
1) ember builds produce a working dist; and.
2) ember cdv:build produces a working build.
Hence the questions.

**Comment by zxcware** [comment]
@alexblom This is my observation: If you run 'ember server' and hit localhost:4200 in browser, it would work. But if you shut down the server, simply opening the index.html file in browser wouldn't work, a blank screen showing up. I guess this might be what you said 'ember builds are not working'?

The reason is: the paths for all resource files are based on the serving directory: '/' instead of relative paths. Ember seems to assume a server is running to serve resource files at '/'. I don't know if there is any configuration to change it or some tricks to get around it.

**Comment by alexblom** [comment]
I just took a deeper look at your app. The builds are fine, it was actually Mirage requests failing.

You need to edit config/environment.js to have locationType of hash (https://github.com/isleofcode/super-rentals-cordova/pull/1/commits/277271b6cc26ab5edf5ad945ff35880f153ff91d). Once that is done, you can run ember cdv:build as expected. The build seems to work correctly, and the background changes. Mirage requests still failed though.

To fix Mirage, urlPrefix needed to be defined: https://github.com/isleofcode/super-rentals-cordova/pull/1/commits/20ad46b9a458d16eb8ca35dc6b59b8e9aa184585

Here is the super-rentals with working ember-cordova: https://github.com/isleofcode/super-rentals-cordova/pull/1/files

**Comment by zxcware** [comment]
Oh yeah! It works by setting locationType to hash and adding urlPrefix in mirage!

Now, ember-cordova is backed with emberjs official example! I guess we can update the README and tell the folks we have a working ember-cordova example!

@alexblom, thank you!

**Comment by alexblom** [comment]
np, and go for it with the README. Perhaps note that it is not at all optimized for hybrid performance - is just an example of using the container.
