### ISSUE TITLE
Workflow 

### ISSUE THREAD

**Issue by gmourasilva** [isleofcode/ember-cordova#50]
Sorry for posting this here. Not sure if this is the right place

Here is what I'm doing: 

I start my ember server and create the UI like a webapp then I run `ember cordova run ios --device` to run in my iPhone.

My API is a Rails app running in my own computer, then I deployed the api to Heroku and changed the API address point based on the environment.

It looks like that the run option doesn't know my production environment. 

Now, I run `ember cordova:build --environment=production --platform=ios && ember cordova run ios --device` to simulate but this is slow. 

Is that workflow correct? Is there any way to improve this workflow?

I also tried the live reload 

`ember cordova:serve --platform=ios` and 
`ember cdv:open —-platform=ios`

But it doesn't look as I was looking for.

Any suggestions to improve the workflow?

**Comment by AlexBlom** [comment]
I've found running simulations directly from Xcode to be a little bit faster.

If you are making changes to the Ember app only (e.g. not adding cordova plugins) live reload will save you from needing to rebuild each time, you will only need to build once. 

Were you having problems making live reload work, or it didn't fit your needs?

**Comment by gmourasilva** [comment]
Thanks for the fast answer.

It looks like I finally got a workflow. 

````
ember cordova:serve --platform=ios 
ember cdv:open —-platform=ios
````

Running on the simulator looks faster then in the device
Thanks for your help 😄
