### ISSUE TITLE
What's the pattern for building an app that may or may not be run in a cordova context?

### ISSUE THREAD

**Issue by machty** [isleofcode/ember-cordova#53]
Presumably we should wait for the deviceready promise in the cordova service within application route's `beforeModel` hook, but what if you're writing an app that has a cordova target AND a web app target? Would be nice if the cordova service gave you a promise to wait for that resolved immediately if it detected that it _wasn't_ running in a cordova context.

**Comment by AlexBlom** [comment]
Today, you would just use platform.isWebView. Perhaps it needs a better name?. 

You don't need to wait for deviceReady in this context. The property is defined by window.cordova/phonegaps presence, and cordova.js is always included before ember-app.js. (I should write a stricter test case for this actually)

Am I grokking or did I miss something?

**Comment by sandstrom** [comment]
We've used Ember + Cordova for a while and I was happy to find this addon. It seems very useful!

I have the same question as Machty. One thing that would be great for the readme is a list of things that this addon does automatically (perhaps that's nothing?). Right now it's a bit opaque (without going through the source).

***

*I think it's great that you keep some things outside this repo (for example https://github.com/isleofcode/ember-cordova-network) and that many things seems to be opt-in already.*

**Comment by sandstrom** [comment]
friendly ping @alexblom

**Comment by alexblom** [comment]
@sandstrom  - don't know how I missed this the first time. I'm slowly fixing the docs, but right now the lib is mostly a CLI for building/serving with an assumption you are in a pure cordova context. All of the plugins are external, and I'm working on better documenting that ecosystem this week.

If you can perhaps describe your use case to me, I'd be able to better understand where the lib would apply / or what low hanging fruit we have that I've simply not considered.

**Comment by sandstrom** [comment]
That sounds awesome!

We build a desktop and mobile app, most code is shared. Using an ENV variable to toggle between the two, plus a custom ember-cli addon which handles some of the differences. The mobile client output can be deployed as a mobile website or 'wrapped' in cordova and deployed natively.

From our perspective the ability to enable/disable all parts of `ember-cordova` plus some documentation around the moving pieces would be awesome. Then we could enable all (or most) in our mobile cordova builds, but not desktop or mobile web context.

**Comment by sandstrom** [comment]
friendly ping @alexblom 😃

**Comment by runspired** [comment]
I'm pretty sure checking the presence of `window.cordova` is brittle, looking for docs but I believe it's async.

**Comment by runspired** [comment]
according to docs it is not async, I suspect it was at one point but I'm glad it is not anymore :)

**Comment by Kilowhisky** [comment]
To add to this the ability to dynamically load the cordova.js file (if its not already) would be great as you'd then gain the ability to deploy a single web code base and then just have the config.xml file point to the site and if its detected to be mobile it could load the cordova.js file.

**Comment by runspired** [comment]
@Kilowhisky actually, what this does is ship an empty cordova.js file for situations in which you aren't building for cordova :D

**Comment by runspired** [comment]
(because you can't load cordova.js async, that would seriously wreck a lot of things)

**Comment by Kilowhisky** [comment]
Bummer. I'd really like to build and target both web and cordova at the same time so that i just push a webserver update instead of having to rebuild and resubmit my app every time i want to push an app update.  

I.E. `<content src="https://myappdomain.com/"/>`

**Comment by runspired** [comment]
@Kilowhisky nothing stops you from doing that....

**Comment by alexblom** [comment]
Exactly. You can still achieve this with what we have today, but I'd be curious to hear where it is breaking down for you so we can improve the cli / docs. 

What you are describing is basically just a vanilla js or before ember hook that replaces the ember.js source with a remote file. Note that is is questionable whether this is allowable in the apple ecosystem - you see yes and no documented unofficially, but I'm not aware of people being banned for it. 

It's probably polite for minor releases and more problematic for major releases.

**Comment by sandstrom** [comment]
@alexblom I scanned the source quickly, and in our case being able to toggle the services on/off (ideally individually) via `environment.js` would be enough (I think). Probably also the `cordova.js` injection.

That way we can selectively disable/enable things for various build targets (e.g. cordova mobile, regular desktop or mobile web).

On the documentation side, just stating what will occur automatically when the addon is included, and what parts are 'on demand' would be enough.

E.g. saying that service A, B and C + the cordova.js file will be included automatically, but each can be disabled via settings X, Y, Z in environment.js. In addition, the addon enables these CLI commands: O, P, Q.

I think this is already 99% useful for people doing both desktop and mobile. Just a few lines of documentation on what to expect, plus the ability to toggle some things and it'll be 100% useable in both contexts.

Is this a helpful explanation?

**Comment by alexblom** [comment]
Understood / appreciated. Have a few doc updates coming now I'm back & core issues have been squashed.

The cordova.js injection should only happen when running ember cdv:build (standard ember builds will not inject).

Re: the standard library services being imported, we need to better support not injecting the service:cordova.

**Comment by alexblom** [comment]
Final note on this: As of 0.4.0 - planned for Jan 2 - only the `device/platform` service will be injected by default, and other plugins have been moved to standalone addons. Details: https://github.com/isleofcode/ember-cordova/releases/tag/0.3.13

This solves the second problem of our default services (e.g. splash) also being injected. A standard `ember build` will include no assets outside of `device/platform`, which we consider an essential primitive. 

I'm going to close this as I think that solves both challenges we used to have, but please re-open if that is not the case for you.

**Comment by sandstrom** [comment]
Sounds excellent @alexblom! 🛥 

Will make it way easier to use in hybrid apps (mobile + desktop or mobile native + mobile web).
