### ISSUE TITLE
build --store-password option doesn't work

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/ember-cordova#6]
Pops up a GUI window to prompt for it instead. If you check the `release-signing.properties` file generated, the `key.store.password` property isn't listed. Works if you run `cordova build android` instead with `--storePassword` directly. `--store`, `--alias` and `--password` all work fine, so I assume it's to do with the camel case mangling.

**Comment by alexblom** [comment]
Thanks for the report, replicated. Should have a resolution in the coming week.

**Comment by alexblom** [comment]
This is something we will ultimately be handling corber side.
