### ISSUE TITLE
'ember install ember-cordova' doesn't work

### ISSUE THREAD

**Issue by hoboman313** [isleofcode/ember-cordova#61]
```
ember install ember-cordova
Installed packages for tooling via npm.
Cannot find module 'splicon/lib/icon-task'
Error: Cannot find module 'splicon/lib/icon-task'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\***\***\node_modules\ember-cordova\lib\commands\mak
e-icons.js:3:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I am on "ember-cli": "2.5.1"

**Comment by AlexBlom** [comment]
Taking a look, expect a release today.

**Comment by AlexBlom** [comment]
Fixed in 0.1.09

**Comment by hoboman313** [comment]
Cool it worked out.

So I'm a web dev, diving into hybrid mobile apps for the first time. I'm partly using your ember conf video for guidance here ( really good stuff btw ) with ember + cordova. Was just going through the "Getting Started" section and noticed that "ember cdv platform add android" doesn't work right away because the id of the  app in config.xml doesn't follow the _com.company. Name_ pattern and spits out:
```
ember cdv platform add android
Running 'cordova platform add android'
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name
File: C:\Windows\system32\cmd.exe
Command failed: cordova platform add android
Error: Command failed: cordova platform add android
    at checkExecSyncError (child_process.js:469:13)
```
Not sure if this is by design. I'm on cordova 6.2.0.

**Comment by AlexBlom** [comment]
Was this an existing cordova project, or did ember-cordova init it for you?

Also what is the value of id in <widget>, probably line 2 of your config.xml file?

**Comment by hoboman313** [comment]
New cordova project created with 'ember install ember-cordova'. The value of the id in widget was the same as its <name>. I'm looking at the ember-cli-cordova docs and their cordova-init generator actually takes the com.* package name as a parameter.
