### ISSUE TITLE
Uploading the apk generated gives the following error - You uploaded an apk with an invalid signature. 

### ISSUE THREAD

**Issue by flynsequeira** [isleofcode/ember-cordova#7]
How do I sign my unsigned release apk? I have a long key, which I'm not sure where to use. I've incremented the version number and name in the config.xml. used  

> ember cdv:build --platform=android --environment=production --release

 to build it.

**Comment by AshMartian** [comment]
I use this bash script I found on Stackoverflow. Installs on device at the end (Android). You can replace with iOS commands.

```
#!/bin/sh
echo "Phonegap to Signed APK ---- b@agencys.eu // Benjamin Rathelot\n"
printf "Project dir : "
read DIR
printf "Version: "
read VER
printf "Project key alias : "
read ALIAS
cd $DIR/
echo "Building ${VER//./} version"
ember cordova:build --platform=android --cdv-version-code="5${VER//./}" --buildId=$VER --release --force
OUTPUT="ember-cordova/cordova/platforms/android/build/outputs/apk/"
keytool -genkey -v -keystore my-release-key.keystore -alias $ALIAS -keyalg RSA -keysize 2048 -validity 10000 -noprompt -storepass $ALIAS
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore $OUTPUT/android-armv7-release-unsigned.apk -storepass $ALIAS $ALIAS
rm $OUTPUT/App-$VER-signed.apk
~/Library/Android/sdk/build-tools/24.0.0/zipalign -v 4 $OUTPUT/android-armv7-release-unsigned.apk $OUTPUT/App-$VER-signed.apk
adb uninstall com.company.name
adb install $OUTPUT/App-$VER-signed.apk

```

**Comment by flynsequeira** [comment]
I'll checked this out. The code was actually android, not ios. I edited it now. 
But I got an error:-
Got an error: abd: command not found. Also, what goes into ALIAS?

**Comment by flynsequeira** [comment]
Got an error: abd: command not found

**Comment by AshMartian** [comment]
Make sure you have the Android adb in your path. The last two lines aren't needed if you are only looking for the signed APK. Found in: project-dir/ember-cordova/cordova/platforms/android/build/outputs/apk/

ALIAS is your keystore alias. Make sure this is the same for releases, you could statically set this in the script. 
Also highly recommend backing up the generated keystore, and enrolling in the Google key management. Lost my key once, was a nightmare.

**Comment by flynsequeira** [comment]
Will try this. Thanks. The  information we put at
 keytool -genkey -v -keystore my-release-key.keystore -alias $ALIAS -keyalg RSA -keysize 2048 rompt -storepass $ALIAS
Can it be anything? 
The step 
rm $OUTPUT/App-$VER-signed.apk
did not work because the file doesn't exist. 
and there was no signed apk generated. After uploading the same unsigned apk I get this error: 'You uploaded an apk that is not zip aligned. You weill need to run a zip align tool on your apk and upload it again' . Doing that for now.

**Comment by AshMartian** [comment]
Yup, it can be any string. As long as it is consistent. I recommend using something different for the storepass, I changed the script above to ask for a password instead of using the alias.

**Comment by flynsequeira** [comment]
@blandman Ok noob question, because the project was handed over to me. But I was given a key that kind of looks like this. I assumed it was one of the three.
(not exactly the same)
oi39.ElqNBBjc72BiKRprL9r4IpVKvtKxT-IioEpVlpW9FnoeKd8Do3jdoce93_komdho30cn_jd003j......lsiiwk93si0s-D3g
Is the content of appname.keystore something like this?
I'm assuming this is the apk key. Do let me know how I can approach from here. Thank you.

**Comment by AshMartian** [comment]
Ah I see. If you are trying to update an app on the Google Play store, it is important to use the same key or it will be rejected. 

Use the keytool to identify the alias. You should be able to do something like this, `keytool -list -v -keystore appname.keystore`
You should see Alias names listed. Use this as the alias in the script.
Replace "my-release-key.keystore" in the script with your "appname.keystore" as well.
Do you have the keystore file, or just the key string?

**Comment by flynsequeira** [comment]
Just the keystring. Is that a problem?

**Comment by alexblom** [comment]
It looks like this issue is signing related. You will need the same key.

If you did not sort it out please feel free to re-open or jump over to github.com/isleofcode/corber
