### ISSUE TITLE
git ignore needed

### ISSUE THREAD

**Issue by optikalefx** [isleofcode/ember-cordova#79]
Right now a ton of built cordova files get added to your repo. ideally, you would leave the platforms folder empty, or leave the platform.json file in there, and then an npm install post step would run the ember cordova add platform's as needed.

**Comment by anulman** [comment]
Interesting. The `.gitignore` file [from the blueprints](https://github.com/isleofcode/ember-cordova/blob/master/blueprints/ember-cordova/files/__root__/ember-cordova/.gitignore) is being installed as `.npmignore`:

```
cat ember-cordova/.npmignore
# cordova/platforms
# cordova/plugins
```

On it

**Comment by anulman** [comment]
Seems like this is a known issue with npm: https://github.com/npm/npm/issues/1862#ref-issue-77576849

Best solution will be to manually write `ember-cordova/.gitignore`, probably running as a `Task` in the `afterInstall` hook: https://github.com/isleofcode/ember-cordova/blob/master/blueprints/ember-cordova/index.js

I can get to this soon, but probably not this week. @optikalefx in the interim, consider ignoring the dirs listed above:

```
# ember-cordova/.gitignore
cordova/platforms
cordova/plugins
```

**Comment by RobIsHere** [comment]
It seems like the www directories in cordova and in platforms contain build files. Is it safe to .gitignore them, too?

**Comment by optikalefx** [comment]
Yea and if we ignore those 2 dirs, then we can't re-install the app. Since plugins are only found in the plugins folder. We can't really ignore those.

**Comment by RobIsHere** [comment]
@optikalefx i experienced the same after i renamed .npmignore to .gitignore.

My gut is telling me that the content of the .gitignore should look like:

#ember-cordova
cordova/platforms
cordova/platforms/*/www
cordova/www

But I'm not sure about it at all because i don't no nothing about ember-cordova build steps.

**Comment by optikalefx** [comment]
yea the problem with this is that there isn't a way to have ember-cordova re-do the build AFIK. You could only use those plugin files as reference, remove all if it by hand then re-install ember-cordova then add all the plugins again.

**Comment by alexblom** [comment]
```
Yea and if we ignore those 2 dirs, then we can't re-install the app. Since plugins are only found in the plugins folder. We can't really ignore those.
```

Can you elaborate on this? We never check the plugins in an always gitignore them.

If you install a plugin with --save (or soon, ember cdv:plugin add), they will be saved to your config.xml. You can then run cordova prepare or ember cdv:prepare to re-install plugins, much like --save & npm install.

**Comment by optikalefx** [comment]
@alexblom huh didn't know that. Does that work for plugins with variables?

**Comment by alexblom** [comment]
Yep! So long as you config the xml correctly, installing plugins by the CLI ensures this is the case.

A lot of people miss this, which is why on #98 I'm setting it up so:
`ember cdv:plugin add / ember cdv:platform add`

Will auto persist plugins/platforms to config.xml on your behalf. You will be able to use ember cdv:prepare as normal on project restores.

**Comment by AmilKey** [comment]
We use this gitignore
```
ember-cordova/cordova/platforms/
!ember-cordova/cordova/platforms/.gitkeep
ember-cordova/cordova/plugins/
!ember-cordova/cordova/plugins/.gitkeep
ember-cordova/cordova/www
!ember-cordova/cordova/www/.gitkeep
```
