### ISSUE TITLE
Building ios on ember-cordova giving error - The following build commands failed: Check dependencies

### ISSUE THREAD

**Issue by flynsequeira** [isleofcode/ember-cordova#8]
The line where the error occures gives error: 
Code Signing Error: Signing for "Application-nameInTheSameFormat" requires a development team. Select a development team in the project editor. Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
Tried building for another application, got the same error. Any idea about this?

**Comment by alexblom** [comment]
This means you do not have signing profiles configured. Open the project in Xcode and set your development team or configure per: http://corber.io/pages/workflow/building

Once  I merge this branch in corber none of it will be necessary: https://github.com/isleofcode/corber/pull/412
