### ISSUE TITLE
Passing --environment=production does not trigger a release build

### ISSUE THREAD

**Issue by adamniedzielski** [isleofcode/ember-cordova#81]
I'm running:

```
ember cordova:build --platform=android --environment=production
```

According to this line https://github.com/isleofcode/ember-cordova/blob/59bc6c00e473e2083cf4cfd34727b7468d0c0187/lib/tasks/cordova-build.js#L11 it should append ```--release``` to the Cordova command.

However, when this function is invoked (https://github.com/isleofcode/ember-cordova/blob/59bc6c00e473e2083cf4cfd34727b7468d0c0187/lib/commands/build.js#L57) the environment parameter is not passed, so this condition is always false (```undefined === "production"```)

**Comment by optikalefx** [comment]
I don't think you always want production environment to be built as release. I think it should be a separate option as it's a separate post process to building for production.

**Comment by alexblom** [comment]
I've been merging our work from last week (@anulman, @runspired & I hacked on this from Montreal) and will be some changes here once completed.

Moving forwards, a production build will not trigger a release unless you append the --release flag.

I'm on a red eye flight this evening and plan on having the release done / updating the documentation by then. I'll close the issue once out.
