### ISSUE TITLE
Error when generating index.html

### ISSUE THREAD

**Issue by jcmartinezdev** [isleofcode/ember-cordova#9]
Hi all,

I've found an error when building my application, on the index.html file the scripts and styles are not being found when loading the web view, inspecting the problem I found the following,

The index.html is loaded with this request: "file:///android_asset/www/index.html"
But the scripts and styles are loaded like "file:///assets/vendor-37087b2afe5f10bb81af5c2d929e1dd2.css"

So part of the route gets missed, and therefore the application is not working.

I've tried to fix the path in the index.html by adding: /android_asset/www to load the files but then I countered problems when loading the images from CSS files

Anyone else encountered this issue, anyway to fix it?

Thanks

**Comment by LiShuxue** [comment]
Hi friend, 
Do you know how to fix this issue ？ I met the same problem. Some script file load like  "file:///assets/vendor....  ", so it cannot be loaded and the application doesn't working.
I don't know why, maybe some configuration is wrong. Do you have any idea ？ thanks

**Comment by jcmartinezdev** [comment]
Hi @LiShuxue ,
To solve all my related topics I did 2 things, first,
in config/environment.js, change: RootURL: '/', to rootURL: ''

Second, in all my scss I had to change URLs, as I was referencing them like:

"/assets/banners/bammer1.png" to "banners/banner1.png"

Hope that helps

**Comment by LiShuxue** [comment]
thank you.
Actually, i already change the rootURL to ' ',but it still not working.
I use ember-engines in my application, when i load the engine file ,it will load like "file:///engine-dist/....", but it cannot load the file.

**Comment by jcmartinezdev** [comment]
I don't have that much experience with engines... looks like a similar problem, good luck with it
