### ISSUE TITLE
docs - how to use splash screens

### ISSUE THREAD

**Issue by optikalefx** [isleofcode/ember-cordova#91]
It should be noted in the docs how to use splash screens and icons. It doesn't match the docs for cordova-plugin-splashscreen. In that it says to add XML configs for splashscreen locations, but b/c those don't match that fails the build. The correct thing seems to be to not include any extra xml.

Also I recommend adding links to https://github.com/AlexDisler/cordova-splash and https://github.com/AlexDisler/cordova-icon for generating the images. As a handy helpful tip for cordova folk.

**Comment by alexblom** [comment]
Icons are currently supported with make-icons: https://github.com/isleofcode/ember-cordova/blob/master/docs/services/icons.md.

I'll be doing a similar pattern with splash.  Wwe're integrating stuff like this into the CLI and handling config.xml changes on your behalf. The plan is you won't need to think - just run cdv:make-splash and have everything configured.
