### ISSUE TITLE
Node 0.1x support

### ISSUE THREAD

**Issue by alexblom** [isleofcode/ember-cordova#92]
Library today requires Node 3 || 4. We probably need to support 0.1x or document lack of support given issues like #84.

@anulman / @runspired thoughts?

**Comment by anulman** [comment]
Ember requires 0.12.x+; seems like Cordova supports the same. Ideally, I think we should support 0.12.x+.

Practically though, where / why are we breaking? Can we add a test target on Travis to inspect?

**Comment by alexblom** [comment]
Handled as of 0.2.10
