### ISSUE TITLE
Geolocation features no longer working after latest update.

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#96]
It is quite weird, all geolocation features are not working when built for android even tho i did `ember  cordova plugin add cordova-plugin-geolocation`

it all work fine, all i did was:
upgraded cordova to 6.3.0 frm 6.2.0
upgraded to ember 2.7
upgraded to ember-cordova 0.2

**Comment by alexblom** [comment]
Can you elaborate a little more on which geolocation features are failing, and how you are expecting to call them?

If you have a sample project somewhere that'd be great.

Ty.

**Comment by v3ss0n** [comment]
i will make a sample.

**Comment by denzo** [comment]
I was just about to post a new issue regarding geolocation and saw this.

**Comment by v3ss0n** [comment]
Thanks , that is the Same problem at me , 
What weird is it works fine in normal cordova build , without ember cordova.

**Comment by alexblom** [comment]
I've tried adding this block to the super-rentals example, and it worked with coordinates.

Perhaps take a look at this diff and let me know what you've done different: https://github.com/isleofcode/super-rentals-cordova/compare/feat-geolocation?expand=1 

To install and test this branch yourself:
```
npm install && bower install
ember cdv platform add iOS
ember cdv:prepare
ember cdv:build
```

**Comment by denzo** [comment]
1st thing, I didn't realize that I had to install `cordova plugin add cordova-plugin-geolocation` :)

2nd, `<plugin name="cordova-plugin-geolocation" spec="~2.2.0" />` wasn't added automatically to the cordova's config.xml

All works as expected now. Thanks for assistance @alexblom, loving your work!

Any ideas on these deprecation warnings which appeared with geolocation plugin?
![screen shot 2016-08-10 at 7 28 15 pm](https://cloud.githubusercontent.com/assets/1874772/17548871/31ac4276-5f31-11e6-9021-3d1e54805294.png)

**Comment by alexblom** [comment]
Thanks. Yeah, if you install a plugin in cordova, the default is that it is not saved to config.xml. If you want that to happen, you need to append --save.

Once I merge in #98 you will be able to run ember cdv:plugin add and that will be automated for you.
