### ISSUE TITLE
I can't run this project to contribute

### ISSUE THREAD

**Issue by villander** [isleofcode/ember-cordova#99]
i'm up-to-date with branch master of this repo. and still not have a dummy app

I can't run this project :(

#30

**Comment by alexblom** [comment]
Our current testing story does not use a dummy app, rather it tests cordova/ember functions. As we expand in function and time permits (mostly the latter), a full testing mock is going to be required.  

Per #30, ember s likely won't run in the add-on while this is the case - but I'm not sure you would need to.  For now the test cases should cover what you need, and there is a sample integration with super-rentals here: https://github.com/isleofcode/super-rentals-cordova/tree/feat-geolocation

Feel free to open an issue with a specific issue you are having.
